// src/data/neuroWeaknessDrills.ts
/**
 * Neurology drills — the "weakness" domain (Weakness: nerve, junction & muscle)
 * of the Neurology drill bank.
 *
 * Each drill is one presentation (acute flaccid weakness, fluctuating weakness,
 * ascending paralysis, mixed UMN/LMN signs, proximal weakness, relapsing CNS
 * episodes). The student sorts the causes by LEVEL of the motor unit — nerve,
 * junction, muscle, cord/toxin — with the pattern clue that separates each,
 * then the antibody, the associated tumor, the one confirming test and the
 * treatment. `org` is "Differential" or "Diagnosis & treatment" so the Browse
 * list splits the two kinds of drill.
 *
 * ITEM RULE — items are "<recall head> — <why / clue>". Only the head is graded
 * (gradableItem in drillProgressCore), so it is the shortest phrase a student
 * would actually write; "/" in a head lists alternative spellings any one of
 * which earns credit. Numbers, cut-offs and nuance live after the dash or in
 * pearls, which are shown on reveal and never graded. Heads within one drill
 * must not credit each other — asserted in __tests__/neuroGuidelineDrills.test.ts.
 *
 * Standard board values; institutional protocols vary. Educational use only.
 * GENERATED by the neuro drill workflow (2026-09-15) from standard shelf sources
 * (AAN practice guidelines, MGTX, Blueprints/First Aid-level facts).
 */
import type { GuidelineDrill } from "./guidelineDrillBank";

const DIFFERENTIAL = "Differential";
const DX_TX = "Diagnosis & treatment";
const REVIEWED = "2026-09-15";

export const NEURO_WEAKNESS_DRILLS: GuidelineDrill[] = [
  // ───────────────────────── ACUTE WEAKNESS BY PATTERN ─────────────────────────
  {
    id: "weakness-acute-flaccid-differential",
    domain: "weakness",
    name: "Acute weakness by pattern",
    org: DIFFERENTIAL,
    prompt: `Three patients present the same week with new weakness: a 24M with two days of tingling feet, then leg weakness and absent knee jerks, two weeks after a diarrheal illness; a 44F whose ptosis and diplopia are worst every evening; and a 13M back from a camping trip with blurred vision, dilated pupils, constipation and weakness that started in the face and is moving down.\n\nName the diagnosis each weakness pattern points to, sorted by level of the motor unit (nerve, junction, muscle, cord/toxin), with the clue that separates it.`,
    keyPoints: [
      {
        group: "Peripheral nerve",
        items: [
          "Guillain-Barré / GBS — ASCENDING symmetric weakness + areflexia over days, often after Campylobacter; CSF protein high with normal cells; LP and EMG/NCS confirm it",
          "CIDP — the GBS vignette that has lasted months or relapses; unlike GBS it responds to steroids as well as IVIG",
          "Toxic neuropathy — vincristine or cisplatin, then distal sensorimotor (± autonomic) neuropathy; also lead, arsenic, isoniazid; 'toxic neuropathy' is the NBME answer",
          "Tick paralysis — child, ascending flaccid paralysis over hours with a NORMAL CSF; engorged tick on the scalp — remove it and strength returns within hours",
        ],
      },
      {
        group: "Neuromuscular junction",
        items: [
          "Myasthenia gravis — FATIGABLE ptosis, diplopia, dysphagia worst late in the day; cannot hold upgaze 60 s; reflexes and sensation normal; anti-AChR (postsynaptic)",
          "Lambert-Eaton — proximal weakness that IMPROVES with use (rises from the chair on the third try), hyporeflexia, dry mouth; anti-VGCC (presynaptic); small cell lung cancer",
          "Botulism — DESCENDING paralysis with dilated fixed pupils, diplopia, dysphagia, dry mouth, constipation; canned food (or honey in an infant); toxin cleaves SNARE → no ACh release",
          "Organophosphate — farm worker or suicidal ingestion: DUMBBELSS + fasciculations then weakness (nicotinic); atropine first, then pralidoxime",
        ],
      },
      {
        group: "Muscle",
        items: [
          "Polymyositis — symmetric PROXIMAL weakness (stairs, combing hair) with high CK and ESR, no sensory or reflex loss; anti-Jo-1",
          "Myotonic dystrophy — grip that will not let go, frontal balding, cataracts, testicular atrophy, arrhythmia; CTG repeat (DMPK), anticipation",
          "Periodic paralysis — attacks of flaccid weakness after a carbohydrate load or rest after exercise; potassium low (or high) during the attack; thyrotoxic form in Asian men",
        ],
      },
      {
        group: "Cord & toxin",
        items: [
          "Transverse myelitis — bilateral leg weakness with a SENSORY LEVEL, bladder retention and hyperreflexia (after spinal shock); post-viral or SLE; MRI spine",
          "Tetanus — SPASTIC paralysis: trismus, risus sardonicus, opisthotonos; toxin blocks GABA/glycine release; dirty wound or home-cut umbilical stump",
          "Tetrodotoxin — pufferfish: perioral paresthesia then flaccid paralysis and respiratory failure; blocks sodium channels",
          "Polio / poliomyelitis — asymmetric flaccid weakness of one limb with fever and meningism, NO sensory loss; anterior horn; unvaccinated",
        ],
      },
    ],
    pearls:
      "Reflexes and sensation do the sorting: nerve = reflexes lost with sensory symptoms (GBS, toxic; tick paralysis loses reflexes but sensation is largely spared); junction = both normal (MG, LEMS, botulism); muscle = reflexes kept, sensation normal, CK often high; cord = hyperreflexia with a sensory level. Direction is the second sort — GBS climbs, botulism descends from the cranial nerves, and pupils separate them (dilated and fixed in botulism, normal in GBS and MG). Fatigable vs facilitating: MG tires with use, LEMS strengthens with use. A young patient with a diarrheal prodrome and tingling feet is GBS even when the stem never mentions Campylobacter. Tetanus is the one spastic toxin (blocks inhibitory Renshaw-cell release); botulism and tetrodotoxin are flaccid. Any acute weakness with dysphagia or a falling vital capacity needs serial FVC/NIF and a monitored bed before the diagnosis is confirmed.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── MYASTHENIA VS LAMBERT-EATON ─────────────────────────
  {
    id: "weakness-mg-vs-lems",
    domain: "weakness",
    name: "Myasthenia gravis vs Lambert-Eaton",
    org: DX_TX,
    prompt: `44F office worker with diplopia, hoarseness and ptosis that all worsen through the afternoon; she cannot sustain upgaze for 60 seconds. Her neighbor, a 62M smoker, must try three times to rise from a chair but grows stronger with each attempt, has absent knee jerks and a dry mouth.\n\nList the features, antibodies, associated tumors, tests and treatments that separate myasthenia gravis from Lambert-Eaton syndrome.`,
    keyPoints: [
      {
        group: "Myasthenia gravis",
        items: [
          "Anti-AChR / acetylcholine receptor antibody — POSTsynaptic nicotinic receptor block; positive in ~85% of generalized MG; when both are listed, choose the antibody over the Tensilon test",
          "Ptosis / diplopia worse late in day — fatigable ocular, bulbar (dysphagia, hoarseness) then limb weakness; ice-pack on the lid improves ptosis; normal reflexes and pupils",
          "Thymoma — 10–15% of MG; chest x-ray then CT chest after every new diagnosis; thymic hyperplasia in most of the rest",
          "Anti-MuSK — muscle-specific kinase; AChR-negative MG with bulbar, facial and neck weakness; no thymoma, poor response to pyridostigmine; rituximab",
        ],
      },
      {
        group: "Lambert-Eaton",
        items: [
          "Anti-VGCC / voltage-gated calcium channel antibody — PREsynaptic; less ACh released per impulse; hyporeflexia and autonomic dryness (dry mouth, impotence)",
          "Improves with use / activity / incremental response — proximal leg weakness that strengthens after repeated effort; absent reflexes return after 10 s of exercise",
          "Small cell lung cancer / small cell / SCLC — the paraneoplastic driver in ~50–60%; CT chest in every LEMS patient and repeat it if negative; smoker over 50",
        ],
      },
      {
        group: "Diagnosis",
        items: [
          "Upgaze / upward gaze / sustained gaze — hold upgaze 60 seconds: MG fatigues and the ptosis worsens, LEMS holds it without difficulty",
          "Repetitive nerve stimulation / EMG — MG: DECREMENT at low-frequency (3 Hz) stimulation; LEMS: INCREMENT (>100%) at high frequency or after exercise; single-fiber EMG most sensitive",
          "Neuromuscular junction — the structural answer when the vignette is MG or LEMS and neither disease name is listed",
        ],
      },
      {
        group: "Treatment",
        items: [
          "Pyridostigmine — long-acting acetylcholinesterase inhibitor, first-line symptomatic MG; overdose → cholinergic crisis (DUMBBELSS, fasciculations, weakness)",
          "Thymectomy — always for thymoma; also improves generalized AChR-positive MG under ~65 even without a thymoma (MGTX trial)",
          "Prednisone / immunosuppression — steroids (start low: transient worsening), azathioprine or mycophenolate as steroid-sparing; rituximab for MuSK",
          "IVIG / plasmapheresis — myasthenic crisis (FVC <15–20 mL/kg or NIF weaker than −20 to −30 cmH2O) or preparation for thymectomy; intubate early, stop pyridostigmine while ventilated",
          "Amifampridine / 3,4-diaminopyridine — LEMS symptomatic drug (blocks K+ channels → more ACh release); treating the SCLC improves the weakness",
        ],
      },
    ],
    pearls:
      "Edrophonium (Tensilon, short-acting AChE inhibitor) improves MG dramatically and LEMS barely — but it is historical: on the shelf pick the antibody when both are listed. Myasthenic vs cholinergic crisis both present as weakness; cholinergic adds miosis, salivation, bronchorrhea and fasciculations (edrophonium used to distinguish them — now stop the pyridostigmine and support). Drugs that unmask or worsen MG: aminoglycosides, fluoroquinolones, macrolides, beta-blockers, magnesium, neuromuscular blockers, penicillamine, checkpoint inhibitors — avoid or monitor. Pupils are normal in MG (ocular muscles only), which separates it from botulism. Ocular MG can stay ocular in ~50%; seronegative MG → MuSK then LRP4. LEMS: eyes are spared, legs worst, autonomic symptoms are the giveaway; a normal CT chest does not exclude SCLC — image every 3–6 months for 2 years.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── GBS, CIDP & LOOK-ALIKES ─────────────────────────
  {
    id: "weakness-gbs-cidp-neuropathies",
    domain: "weakness",
    name: "Guillain-Barré, CIDP & look-alikes",
    org: DX_TX,
    prompt: `24M, two weeks after a diarrheal illness, has 3 days of tingling in his feet, then weakness of both legs and now his hands; knee and ankle jerks are absent, sensation is mildly reduced in a stocking pattern, and he has no bladder complaint. CSF: protein 95 mg/dL, 4 WBC/µL.\n\nList the presentation and mechanism, the diagnostic findings, the treatment (and the treatment that is wrong), and the look-alikes with the clue that separates each.`,
    keyPoints: [
      {
        group: "Presentation & mechanism",
        items: [
          "Ascending paralysis / areflexia — symmetric weakness starting distally in the legs and climbing over days, peaks by 2–4 weeks; deep tendon reflexes lost early; paresthesias precede it",
          "Campylobacter jejuni — most common trigger (molecular mimicry with GM1 ganglioside); also CMV, EBV, Zika, HIV; the shelf often omits the prodrome",
          "Schwann cell / segmental demyelination — T-cell and antibody attack on PERIPHERAL myelin (AIDP); the CNS counterpart is MS (oligodendrocytes)",
          "Miller Fisher — variant: ophthalmoplegia + ataxia + areflexia with little limb weakness; anti-GQ1b antibody",
        ],
      },
      {
        group: "Diagnosis",
        items: [
          "Albuminocytologic dissociation — CSF protein high with normal cells (<10); may be normal in week 1; >50 cells → think HIV, Lyme, polio, West Nile instead",
          "EMG / electromyography / nerve conduction studies — confirms alongside LP, abnormal even in week 1 when CSF is still normal: slow conduction, prolonged or absent F-waves, conduction block",
          "FVC / forced vital capacity / NIF — serial bedside spirometry every 4–6 h; FVC <20 mL/kg or NIF weaker than −30 cmH2O → ICU and elective intubation",
        ],
      },
      {
        group: "Treatment",
        items: [
          "IVIG — 2 g/kg over 2–5 days; start once the patient cannot walk unaided; equal to plasmapheresis and easier",
          "Plasmapheresis / plasma exchange — the alternative within 4 weeks of onset; not additive with IVIG (do one, not both)",
          "No steroids / steroids are wrong — corticosteroids do not help GBS (unlike CIDP, MS, transverse myelitis); the classic distractor answer",
        ],
      },
      {
        group: "Look-alikes",
        items: [
          "CIDP — same picture progressing >8 weeks or relapsing; steroids, IVIG and plasma exchange all work",
          "Charcot-Marie-Tooth / CMT — hereditary (PMP22 duplication): pes cavus, hammer toes, foot drop, 'inverted champagne bottle' legs; slow over years, family history",
          "Tick paralysis — child, ascending paralysis over hours with a NORMAL CSF; find and remove the tick — recovery within hours",
          "Transverse myelitis / cord lesion — sensory LEVEL, bladder retention, hyperreflexia and Babinski once spinal shock passes; MRI spine before calling it GBS",
          "Polio / West Nile — ASYMMETRIC flaccid weakness with fever and CSF pleocytosis (cells, not just protein); anterior horn; unvaccinated or summer mosquito exposure",
        ],
      },
    ],
    pearls:
      "Death in GBS is respiratory and autonomic: labile blood pressure, arrhythmia and ileus need telemetry, and the 20/30/40 rule (FVC <20 mL/kg, MIP <30, MEP <40) means intubate before the gases change. Never use succinylcholine (hyperkalemia from denervated muscle). Nadir at 4 weeks, then slow recovery over months; ~85% walk again but 5% die and 10–20% keep deficits. Bulbar and bilateral facial weakness are common (unlike a stroke); bladder involvement early or a sensory level means cord, not nerve. Axonal variants (AMAN, anti-GM1) follow Campylobacter and recover more slowly. CIDP is the one to remember for steroids — a 'GBS' that has lasted 4 months and improved on prednisone. Charcot-Marie-Tooth has no treatment beyond orthotics; diabetic neuropathy is distal, symmetric, sensory-first and chronic.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── MOTOR NEURON DISEASES ─────────────────────────
  {
    id: "weakness-motor-neuron-disease",
    domain: "weakness",
    name: "Motor neuron diseases & mimics",
    org: DIFFERENTIAL,
    prompt: `58M with 8 months of progressive hand weakness and cramps; exam shows tongue fasciculations, wasted intrinsic hand muscles, brisk knee jerks and bilateral Babinski signs, with normal sensation and bladder function. Separately, a 4-month-old is profoundly hypotonic with absent reflexes and a fasciculating tongue.\n\nName the motor neuron diseases and their mimics by age, then the signs, tests and treatment that confirm the diagnosis or rule the mimics out.`,
    keyPoints: [
      {
        group: "Adult",
        items: [
          "ALS / amyotrophic lateral sclerosis — UMN + LMN signs in the same limbs with NO sensory or bladder loss; corticospinal tracts + anterior horns degenerate; 'motor neurons' is the structural answer",
          "Polio / poliomyelitis — anterior horn only: asymmetric flaccid weakness, one wasted short leg decades later (post-polio syndrome); unvaccinated; CSF pleocytosis in the acute illness",
          "Tropical spastic paraparesis / HTLV-1 myelopathy — slowly progressive spastic legs + bladder urgency in a Caribbean or Japanese patient; HTLV-1 serology",
          "Cervical spondylotic myelopathy — the treatable ALS mimic: UMN legs + LMN hands but with NECK PAIN and sensory changes; MRI cervical spine",
        ],
      },
      {
        group: "Pediatric",
        items: [
          "Spinal muscular atrophy / Werdnig-Hoffmann — SMN1 deletion (AR), anterior horns: floppy baby, absent reflexes, tongue fasciculations, alert face; nusinersen or gene therapy",
          "Cerebral palsy — UMN: spastic diplegia with scissoring gait, brisk reflexes, toe walking; prematurity or perinatal hypoxia; non-progressive",
          "Infant botulism — honey or soil spores (<12 months): constipation first, then hypotonia, poor suck, ptosis, sluggish pupils; descending; botulism immune globulin",
          "Duchenne muscular dystrophy — muscle, not neuron: Gower sign, calf pseudohypertrophy, CK in the thousands from infancy with symptoms by age 3–5, absent dystrophin (X-linked); Becker milder",
        ],
      },
      {
        group: "Signs",
        items: [
          "Tongue fasciculations — LMN sign of hypoglossal-nucleus loss: ALS in adults, SMA in infants; never from a cord lesion below the medulla, a myopathy or a junction disorder",
          "No sensory loss / sensation preserved / no sensory findings — any numbness or sensory abnormality in the stem = not ALS (think neuropathy or myelopathy)",
          "UMN + LMN signs / upper and lower motor neuron signs — Babinski, clonus and brisk reflexes in a limb that also has atrophy and fasciculations: the ALS signature",
        ],
      },
      {
        group: "Tests & treatment",
        items: [
          "EMG / nerve conduction studies — fibrillations, fasciculations and denervation in ≥3 body regions with NORMAL sensory conduction; the confirmatory step",
          "MRI cervical spine — excludes the treatable mimics (spondylotic myelopathy, syrinx, tumor) before ALS is diagnosed",
          "Riluzole — glutamate-release inhibitor that extends survival ~3 months; edaravone; noninvasive ventilation and PEG for respiratory and bulbar failure",
        ],
      },
    ],
    pearls:
      "ALS is a clinical diagnosis of exclusion: mixed signs in the same region, spreading, no sensory or bladder involvement, and a normal cervical MRI. Median survival 3–5 years, death from respiratory failure; cognition is usually spared but 10–15% develop frontotemporal dementia (C9orf72). Bulbar-onset ALS (dysarthria, dysphagia, tongue wasting) is worse. A pure LMN picture in an adult may be multifocal motor neuropathy (anti-GM1, conduction block on NCS, IVIG-responsive) — treatable, so look for it. SMA type 1 (Werdnig-Hoffmann) presents under 6 months and dies of respiratory failure by 2 without therapy; the tongue fasciculations, preserved eye movements and normal pupils separate it from infant botulism (ptosis, sluggish pupils), and the absent reflexes from a myopathy. Floppy infant with constipation and a poor suck after honey is botulism (junction), scissoring legs is cerebral palsy (UMN), Gower sign in a 4-year-old boy is Duchenne (muscle).",
    reviewed: REVIEWED,
  },
  // ───────────────────────── MYOPATHY VS POLYMYALGIA ─────────────────────────
  {
    id: "weakness-myopathy-vs-pmr",
    domain: "weakness",
    name: "Proximal weakness: myopathy vs polymyalgia",
    org: DIFFERENTIAL,
    prompt: `50F with 3 months of difficulty climbing stairs and lifting her arms to brush her hair; CK 4,800 U/L, ESR 60. Her 68-year-old mother has shoulder and hip stiffness worst in the morning, normal strength, a normal CK and a new right temporal headache with pain on chewing.\n\nName the muscle disorders that present with proximal weakness, pain or stiffness — inflammatory, genetic, drug and hyperthermic — with the feature that separates each, then the workup.`,
    keyPoints: [
      {
        group: "Inflammatory",
        items: [
          "Polymyositis — symmetric proximal WEAKNESS with high CK; endomysial CD8 T cells; anti-Jo-1 antisynthetase (ILD, arthritis, mechanic's hands)",
          "Dermatomyositis — the same weakness plus heliotrope rash, Gottron papules, shawl sign; perimysial CD4, perifascicular atrophy; anti-Mi-2; screen for occult cancer",
          "Polymyalgia rheumatica / PMR — >50, shoulder and hip girdle PAIN and morning stiffness with NORMAL CK and strength, high ESR; prednisone 15 mg works within days",
          "Giant cell arteritis / temporal arteritis — travels with PMR in ~15–20%: temporal headache, jaw claudication, vision loss; high-dose steroids BEFORE the biopsy",
        ],
      },
      {
        group: "Genetic",
        items: [
          "Myotonic dystrophy — grip or percussion myotonia with DISTAL and facial weakness (DM1), frontal balding, cataracts, testicular atrophy, conduction block; CTG repeat in DMPK, anticipation",
          "Duchenne / Becker — X-linked dystrophin: Gower sign, calf pseudohypertrophy, CK in the thousands from infancy with symptoms by age 3–5, dilated cardiomyopathy; Becker (in-frame) later and milder",
        ],
      },
      {
        group: "Drug & hyperthermic",
        items: [
          "Malignant hyperthermia — succinylcholine or halothane → rigidity, fever, rising end-tidal CO2, rhabdomyolysis; ryanodine receptor (RYR1, AD); dantrolene",
          "Neuroleptic malignant syndrome / NMS — antipsychotic + fever + lead-pipe rigidity + autonomic instability + high CK over days; stop the drug, dantrolene or bromocriptine",
          "Statin myopathy — myalgia ± high CK weeks to months after starting; worse with fibrates or CYP3A4 inhibitors; stop the drug; anti-HMGCR necrotizing myopathy if it persists",
          "Hypothyroid myopathy — proximal weakness, cramps, high CK and delayed ('hung-up') reflex relaxation; TSH belongs in every myopathy workup",
        ],
      },
      {
        group: "Workup",
        items: [
          "Creatine kinase — high in myositis, dystrophy, rhabdomyolysis, hypothyroidism; NORMAL in polymyalgia rheumatica and steroid myopathy",
          "Myositis-specific antibodies / anti-Jo-1 / anti-Mi-2 — Jo-1 = antisynthetase syndrome (ILD, mechanic's hands), Mi-2 = classic dermatomyositis; the shelf's next step with EMG",
          "EMG / electromyography — myopathic pattern: short, small, polyphasic motor units with early recruitment; fibrillations in inflammatory myopathy",
          "Muscle biopsy — definitive: endomysial CD8 (polymyositis) vs perifascicular atrophy (dermatomyositis) vs rimmed vacuoles (inclusion body myositis)",
          "ESR / CRP — high in polymyalgia rheumatica (>40) and giant cell arteritis; there is no specific PMR test — the dramatic steroid response confirms it",
        ],
      },
    ],
    pearls:
      "The shelf's one question: is there WEAKNESS or a HIGH CK? Yes = myositis; pain and stiffness with normal strength and CK in a woman over 50 = polymyalgia rheumatica. PMR + temporal headache or jaw claudication = give high-dose steroids now and biopsy the temporal artery within 1–2 weeks (ischemic optic neuropathy is what you are preventing). Dermatomyositis raises cancer risk (ovarian, lung, GI) — age-appropriate screening plus CT chest/abdomen/pelvis. Inclusion body myositis: man over 50, asymmetric, finger flexors and quadriceps, dysphagia, mildly raised CK, steroid-RESISTANT. Steroid myopathy: proximal weakness with a normal CK in a patient on chronic glucocorticoids — taper, do not add more. McArdle: exercise cramps, myoglobinuria and a second-wind phenomenon with a flat forearm lactate. Treatment of polymyositis/dermatomyositis: high-dose prednisone, then methotrexate or azathioprine; IVIG for refractory disease.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── MS & CNS DEMYELINATION ─────────────────────────
  {
    id: "weakness-ms-demyelinating",
    domain: "weakness",
    name: "Multiple sclerosis & CNS demyelination",
    org: DX_TX,
    prompt: `27F with two prior episodes — blurred vision with pain on eye movement two years ago, and numbness of the left leg last winter — now has diplopia: on right gaze the left eye fails to adduct and the right eye shows nystagmus, though she converges normally. She reports urinary urgency; the left plantar is upgoing.\n\nList the classic findings, the diagnostic tests and mechanism, treatment by phase, and the demyelinating mimics with the clue for each.`,
    keyPoints: [
      {
        group: "Findings",
        items: [
          "Optic neuritis / Marcus Gunn pupil — painful monocular vision loss with red desaturation and a central scotoma; relative afferent pupillary defect; a classic first attack",
          "Internuclear ophthalmoplegia / INO / MLF syndrome — failed adduction on the lesion side with abducting nystagmus, convergence intact (unlike a CN III palsy); bilateral INO in a young adult = MS",
          "Urge incontinence — hyperactive detrusor; the incontinence the NBME pairs with MS (not overflow)",
          "UMN signs / Babinski / clonus — spasticity and brisk reflexes; Lhermitte (neck flexion → electric shock down the spine); Uhthoff (worse with heat or a hot shower)",
        ],
      },
      {
        group: "Diagnosis & mechanism",
        items: [
          "MRI brain and spine / MRI — gold standard, chosen over CSF: periventricular ovoid white-matter plaques (Dawson fingers) disseminated in space and time; gadolinium marks active lesions",
          "CSF oligoclonal IgG bands / oligoclonal bands — supports the diagnosis when the MRI is equivocal; elevated IgG index; usually NEGATIVE in neuromyelitis optica",
          "T-cell attack on oligodendrocytes / oligodendrocyte — autoimmune demyelination of CNS myelin (myelin basic protein); the PNS counterpart is GBS (Schwann cells)",
        ],
      },
      {
        group: "Treatment",
        items: [
          "IV methylprednisolone — acute flare, 1 g daily for 3–5 days (oral low-dose steroids alone are the wrong answer); plasma exchange if steroid-refractory",
          "Interferon-beta / glatiramer — disease-modifying therapy between flares to reduce relapses; newer: natalizumab (PML risk), ocrelizumab, fingolimod",
          "Baclofen — GABA-B agonist for spasticity (tizanidine is the alternative); oxybutynin for urgency, amantadine for fatigue, carbamazepine for trigeminal neuralgia",
        ],
      },
      {
        group: "Mimics",
        items: [
          "Neuromyelitis optica / Devic / aquaporin-4 — bilateral optic neuritis + longitudinally extensive myelitis (≥3 segments), oligoclonal bands negative; anti-AQP4; interferon worsens it",
          "Central pontine myelinolysis / osmotic demyelination — hyponatremia corrected too fast (>8–10 mEq/L in 24 h) → locked-in state, pseudobulbar palsy 2–6 days later",
          "PML / progressive multifocal leukoencephalopathy — JC virus reactivation with CD4 <200, natalizumab or rituximab; multifocal non-enhancing white-matter lesions; restore immunity",
          "Ethambutol — drug optic neuropathy (red-green loss, central scotoma) mimicking MS optic neuritis; also linezolid, amiodarone; digoxin (yellow) and sildenafil (blue) only tint vision; stop the drug",
          "ADEM / acute disseminated encephalomyelitis — child after a viral illness or vaccine: MONOPHASIC encephalopathy with multifocal lesions; high-dose steroids",
        ],
      },
    ],
    pearls:
      "The classic patient is a white woman in her 20s–30s from a high-latitude country with episodes separated in space (different tracts) and time (weeks to years); relapsing-remitting is most common, and pregnancy quiets it. Intermittent headaches plus blurry vision in a 27F with painful eye movement or an RAPD is optic neuritis on the NBME; the same headache with papilledema in an obese young woman is idiopathic intracranial hypertension. INO is pathognomonic for MS in the young; in the old it is a pontine stroke. Uhthoff (heat) and Lhermitte (neck flexion) are MS until proven otherwise. Check B12 and HIV before labeling: subacute combined degeneration gives posterior column loss with Babinski. Neuromyelitis optica is the trap when the bands are negative — the answer is 'antibodies against aquaporin-4', and interferon makes it worse. Natalizumab requires JC-virus antibody screening because of PML. Long-term disability is driven by relapse count, so DMT starts at diagnosis.",
    reviewed: REVIEWED,
  },
];
