// src/data/neuroInfectionToxicNutritionDrills.ts
/**
 * Neurology drills — the "infection-toxic-nutrition" domain (Infections, toxins & nutrition) of the Neurology drill bank.
 *
 * Each drill is one exam presentation — fever with a stiff neck, a
 * ring-enhancing lesion in an HIV patient, a rapidly progressive dementia, a
 * confused alcoholic, a floppy infant, a somnolent cirrhotic — and the student
 * lists the organisms, toxins, vitamins or metabolic causes by host/exposure
 * clue with the treatment the exam wants. `org` is "Infections", "Toxins" or
 * "Nutrition & metabolic" so the Browse list splits the three families.
 *
 * ITEM RULE — items are "<recall head> — <clue>"; only the head is graded
 * (gradableItem in drillProgressCore), so it is the shortest phrase a student
 * would actually write; "/" in a head lists alternative names any one of which
 * earns credit. Numbers, cut-offs and nuance live after the dash or in pearls,
 * which are shown on reveal and never graded. Heads within one drill must not
 * credit each other — asserted in __tests__/neuroGuidelineDrills.test.ts.
 * Vitamin letters and CN numerals do not grade (tokens under 3 characters), so
 * the vitamin heads are the chemical names and B12 is the one numbered form.
 *
 * Standard board values; institutional protocols vary. Educational use only.
 * GENERATED by the neuro drill workflow (2026-09-15) from standard shelf sources
 * (IDSA meningitis guidance, First Aid / NBME-style facts); educational use only.
 */
import type { GuidelineDrill } from "./guidelineDrillBank";

const INFECTIONS = "Infections";
const TOXINS = "Toxins";
const NUTRITION = "Nutrition & metabolic";
const REVIEWED = "2026-09-15";

export const NEURO_INFECTION_TOXIC_NUTRITION_DRILLS: GuidelineDrill[] = [
  // ───────────────────────────── INFECTIONS ─────────────────────────────
  {
    id: "infection-toxic-nutrition-meningitis-csf-treatment",
    domain: "infection-toxic-nutrition",
    name: "Meningitis: CSF, organisms & empiric therapy",
    org: INFECTIONS,
    prompt: `19M college freshman with 12 hours of fever to 39.4 °C, severe headache, photophobia and neck stiffness; a petechial rash is spreading over the shins. GCS 15, no focal deficit, fundi normal.\n\nGive the CSF pattern for each etiology, the organisms by host, the empiric regimen by age, and the findings that mandate a CT before the LP.`,
    keyPoints: [
      {
        group: "CSF patterns",
        items: [
          "Bacterial — glucose LOW (<40 or <40% of serum), protein high, thousands of neutrophils/PMNs; opening pressure high; Gram stain",
          "Viral / aseptic — glucose normal, protein normal or mildly up, lymphocytes; echovirus/enterovirus if vaccinated, mumps if not",
          "Fungal / cryptococcal — low glucose + high protein like bacterial but LYMPHOCYTES; Cryptococcus in HIV CD4 <100 (India ink, CrAg); TB looks the same",
          "Herpes encephalitis / HSV — RBCs and xanthochromia from temporal-lobe hemorrhage on a viral background; CT often negative, EEG temporal spikes",
        ],
      },
      {
        group: "Organisms by host",
        items: [
          "Group B Strep / Streptococcus agalactiae — neonates <1 month, most common; from the birth canal; E. coli (gram-negative rod) is the runner-up",
          "Listeria — neonates, adults >50, pregnancy, immunocompromised; gram-positive rod, unpasteurized dairy; cephalosporins miss it — add ampicillin",
          "Pneumococcus / S. pneumoniae — most common in children and adults; gram-positive lancet diplococci; asplenia, CSF leak, otitis/sinusitis",
          "Meningococcus / N. meningitidis — teens in dorms/barracks; gram-negative diplococci; petechiae, Waterhouse-Friderichsen; rifampin or cipro for close contacts",
        ],
      },
      {
        group: "Empiric treatment",
        items: [
          "Ceftriaxone + vancomycin — everyone >1 month; vancomycin covers resistant pneumococcus; add ampicillin if >50, pregnant or immunocompromised (Listeria)",
          "Ampicillin + gentamicin / ampicillin + cefotaxime — neonates (GBS, Listeria, E. coli); cefotaxime not ceftriaxone (bilirubin displacement); vanc + ceftriaxone is WRONG for GBS",
          "Dexamethasone — with or just before the first antibiotic dose; cuts hearing loss and neurologic sequelae in pneumococcal (and H. influenzae) meningitis",
          "Acyclovir — start empirically whenever encephalitis is on the table (confusion, seizure, CSF RBCs); never wait for the HSV PCR",
        ],
      },
      {
        group: "CT before LP",
        items: [
          "Focal neurologic deficit — mass lesion until imaged; LP with a mass can precipitate herniation",
          "Seizure — new seizure in the past week",
          "Papilledema / fundi not visualized — raised ICP; the NBME trap: fundi cannot be seen → CT, not LP",
          "Altered consciousness / low GCS — confusion that prevents a reliable exam; GCS below 15",
        ],
      },
    ],
    pearls:
      "Order of operations: blood cultures → antibiotics (± dexamethasone) → CT if any red flag → LP. Antibiotics before the LP never make the CSF uninterpretable for the exam; delaying them does kill. Kernig and Brudzinski are insensitive — absent signs do not exclude meningitis. Meningitis vs encephalitis: nuchal rigidity and photophobia vs confusion and seizures; with both, treat both (ceftriaxone + vancomycin + acyclovir). Meningococcal purpura + shock = Waterhouse-Friderichsen (adrenal hemorrhage). Hearing loss is the classic sequela — a child failing school after meningitis gets air-conduction audiometry, not tympanometry. Meningitis can leave a communicating hydrocephalus (arachnoid granulations scarred). Aseptic meningitis with no virus found in a patient on TMP-SMX, NSAIDs or IVIG is drug-induced.",
    reviewed: REVIEWED,
  },
  {
    id: "infection-toxic-nutrition-encephalitis-focal-lesions",
    domain: "infection-toxic-nutrition",
    name: "Encephalitis, abscess & ring-enhancing lesions",
    org: INFECTIONS,
    prompt: `34M with untreated HIV (CD4 60) has 5 days of headache, low-grade fever and new right-arm weakness; contrast CT shows two ring-enhancing lesions in the left basal ganglia. Separately, a 27F with 3 days of fever, confusion and a focal seizure has CSF with 80 lymphocytes and 400 RBCs.\n\nName the causes of encephalitis and of a ring-enhancing lesion by host clue with the treatment for each, then the spinal and venous infections that mimic them.`,
    keyPoints: [
      {
        group: "Encephalitis",
        items: [
          "HSV / herpes simplex encephalitis — fever + confusion + temporal-lobe seizures or aphasia; CSF RBCs, EEG temporal spikes, MRI temporal enhancement; IV acyclovir NOW",
          "Lupus cerebritis — SLE with psychosis, seizures or confusion; anti-dsDNA, low complement; steroids; exclude steroid psychosis and infection first",
          "Anti-NMDA receptor encephalitis — young woman: psychosis, seizures, orofacial dyskinesias, autonomic instability; ovarian teratoma; remove it + immunotherapy",
          "Naegleria / primary amebic meningoencephalitis — freshwater swimming in summer; enters via the cribriform plate; fulminant, nearly always fatal; amphotericin",
          "West Nile / arbovirus encephalitis — mosquito season, elderly; fever, tremor, asymmetric flaccid paralysis (anterior horn); supportive",
        ],
      },
      {
        group: "Ring-enhancing lesions",
        items: [
          "Toxoplasmosis — HIV CD4 <100, MULTIPLE lesions in basal ganglia; treat empirically with pyrimethamine + sulfadiazine (+ leucovorin) and reimage in 2 weeks",
          "Primary CNS lymphoma — HIV, SINGLE periventricular lesion, EBV PCR in CSF; failed toxo therapy; biopsy before steroids (they shrink it)",
          "Neurocysticercosis — Taenia solium EGGS, fecal-oral (pork gives only the gut tapeworm), Latin American immigrant; new seizures, multiple cysts ± scolex, calcifications; albendazole + steroids",
          "Brain abscess — fever + headache + focal deficit; endocarditis emboli, sinusitis/otitis, dental; contrast CT; drainage + IV ceftriaxone + metronidazole (± vancomycin)",
          "Metastasis / glioblastoma — multiple at the gray-white junction (lung, breast, melanoma); GBM is a single irregular butterfly lesion crossing the corpus callosum",
        ],
      },
      {
        group: "Spine & venous mimics",
        items: [
          "Epidural abscess — point tenderness over a vertebra + fever ± leg deficits; IVDU, endocarditis, skin infection; S. aureus; MRI, then drainage + IV antibiotics",
          "Pott disease / vertebral tuberculosis — thoracic vertebral destruction with kyphosis, psoas abscess; immigrant, chronic back pain; RIPE",
          "Cavernous sinus thrombosis — S. aureus from a facial/sinus infection; CN VI palsy first, then III/IV/V1, chemosis, proptosis, goes bilateral; IV antibiotics ± heparin",
          "Mastoiditis — untreated otitis media: postauricular tenderness, pinna pushed up and out; CT temporal bone (not X-ray); drain or it becomes an abscess",
        ],
      },
    ],
    pearls:
      "Contrast CT/MRI is for abscess and tumor; non-contrast CT is for blood. In HIV with a ring-enhancing lesion the exam sequence is: CD4 <100 → treat for toxo → no improvement in 10–14 days (or a single lesion with positive CSF EBV PCR) → biopsy for lymphoma. TMP-SMX started for PJP at CD4 <200 already covers toxo at <100 — same drug, two birds. HSV encephalitis is the one CNS infection where the CT is normal and the patient still dies without acyclovir — treat on suspicion, and check creatinine (crystal nephropathy). Point tenderness over a vertebra on USMLE = epidural abscess, compression fracture or metastasis; MRI with gadolinium is the test, and the answer is never 'X-ray'. Cavernous sinus thrombosis is the abducens palsy with a swollen eye; the ophthalmic veins have no valves, so a nose or tooth infection reaches it.",
    reviewed: REVIEWED,
  },
  {
    id: "infection-toxic-nutrition-slow-viral-prion-exposure",
    domain: "infection-toxic-nutrition",
    name: "Slow viral, prion & exposure infections",
    org: INFECTIONS,
    prompt: `41M with AIDS (CD4 40) has 6 weeks of progressive left-sided weakness, visual loss and personality change; MRI shows asymmetric non-enhancing white-matter lesions without mass effect. Separately, a 64F has 3 months of rapidly worsening dementia with startle myoclonus and periodic sharp waves on EEG.\n\nName the slow, post-infectious, exposure-based, prion and congenital infections by their host or exposure clue and the mechanism or test the exam wants.`,
    keyPoints: [
      {
        group: "Immunocompromised",
        items: [
          "PML / progressive multifocal leukoencephalopathy — JC virus REACTIVATION (not new infection): CD4 <200, natalizumab, rituximab; non-enhancing white matter, no mass effect; restore immunity",
          "HIV-associated dementia / AIDS dementia complex — subcortical: slowed thought, apathy, gait and motor slowing; diffuse atrophy; low CD4 off ART; treat with ART",
          "CMV encephalitis / cytomegalovirus — CD4 <50, periventricular enhancement (ventriculitis), retinitis alongside; ganciclovir",
        ],
      },
      {
        group: "Post-infectious & reactivation",
        items: [
          "SSPE / subacute sclerosing panencephalitis — measles reactivation years later in an unvaccinated child/teen: cognitive decline, myoclonus, periodic EEG; measles antibody in CSF",
          "Tropical spastic paraparesis / HTLV-1 myelopathy — Caribbean or Japan; slowly progressive spastic legs + bladder; same virus as adult T-cell leukemia",
          "PANDAS — tics, OCD or ADHD weeks after strep pharyngitis; the test that proves etiology is anti-streptolysin O titers",
          "Sydenham chorea — rheumatic fever months after GAS: 'autoimmune disorder of the basal ganglia' (cross-reacting antibodies); self-limited; penicillin prophylaxis",
        ],
      },
      {
        group: "Exposure-based",
        items: [
          "Rabies — bat in the bedroom or dog bite abroad; weeks–months later hydrophobia, pharyngeal spasms, agitation → coma; Negri bodies; PEP = wash + immune globulin + vaccine",
          "Angiostrongylus / rat lungworm — raw snails, slugs or contaminated produce (Hawaii, SE Asia); eosinophilic meningitis; supportive ± steroids",
          "Polio / poliomyelitis — anterior horn: asymmetric flaccid paralysis and atrophy of one limb, no sensory loss; Salk = killed IM, Sabin = live oral; efficacy = neutralizing antibodies",
          "Lyme neuroborreliosis / Lyme — tick + erythema migrans weeks before; facial palsy (often bilateral), lymphocytic meningitis, painful radiculitis; serology; doxycycline or IV ceftriaxone",
          "Neurosyphilis — tabes dorsalis (dorsal columns: lightning pains, Romberg, Charcot joints), Argyll Robertson pupils, general paresis; CSF VDRL; IV penicillin G",
        ],
      },
      {
        group: "Prion & congenital",
        items: [
          "CJD / Creutzfeldt-Jakob — dementia over weeks–months + startle MYOCLONUS; PrPc α-helix misfolds to PrPSc β-sheet that templates more; periodic sharp waves, 14-3-3, DWI cortical ribbon",
          "Congenital toxoplasmosis — triad: hydrocephalus + chorioretinitis + DIFFUSE intracranial calcifications; cat litter, undercooked meat; pyrimethamine-sulfadiazine",
          "Congenital CMV — most common congenital infection: sensorineural deafness, PERIventricular calcifications, microcephaly, petechiae, hepatosplenomegaly; valganciclovir",
        ],
      },
    ],
    pearls:
      "CD4 ladder for the HIV brain: <200 PJP prophylaxis and PML, <100 toxoplasmosis/cryptococcus/primary CNS lymphoma, <50 CMV and MAC. PML is 'reactivation of latent infection' — 'acute infection in an immunocompromised host' is the wrong answer; there is no antiviral, only immune restoration. CJD is the distractor whenever a dementia vignette lacks myoclonus — no myoclonus, not CJD; it is transmitted by contaminated instruments and corneal grafts, so prion precautions, and it is uniformly fatal within a year. Sydenham chorea vs PANDAS: chorea after rheumatic fever vs tics/OCD after pharyngitis, both prove GAS with ASO titers. Toxo calcifications are scattered through the parenchyma; CMV's ring the ventricles. Polio questions are vaccine questions: only the live oral Sabin vaccine gives mucosal IgA and can revert (vaccine-associated paralysis), so the US uses inactivated Salk.",
    reviewed: REVIEWED,
  },
  // ────────────────────────── NUTRITION & METABOLIC ──────────────────────────
  {
    id: "infection-toxic-nutrition-vitamin-deficiencies",
    domain: "infection-toxic-nutrition",
    name: "Neurologic vitamin deficiencies",
    org: NUTRITION,
    prompt: `58M with alcohol use disorder is brought in confused, with horizontal nystagmus, bilateral abducens palsies and a wide-based gait; glucose 60. Separately, a 44F 3 years after gastrectomy has numb feet, a positive Romberg test, brisk knee jerks and absent ankle jerks.\n\nName the vitamin or mineral behind each neurologic syndrome with its classic setting, the settings that should trigger the search, and the findings the exam tests.`,
    keyPoints: [
      {
        group: "B vitamins",
        items: [
          "Thiamine — Wernicke (A COW: ataxia, confusion, ophthalmoplegia) and dry beriberi neuropathy; alcoholics, hyperemesis, gastrectomy, refeeding; give BEFORE glucose",
          "Cobalamin / B12 — subacute combined degeneration: dorsal columns + corticospinal + spinocerebellar (spinothalamic spared); reversible dementia; pernicious anemia, vegans, metformin, nitrous oxide",
          "Pyridoxine — isoniazid (also hydralazine, penicillamine) depletes it: neuropathy and seizures; co-prescribe with INH; megadoses cause a sensory neuropathy",
          "Folate — tea-and-toast elderly: macrocytosis WITHOUT neurologic signs (more common than B12 on FM); periconceptional deficiency → neural tube defects",
          "Niacin — pellagra: photosensitive dermatitis, diarrhea, dementia; Hartnup, carcinoid syndrome, isoniazid, alcoholism",
        ],
      },
      {
        group: "Fat-soluble & minerals",
        items: [
          "Vitamin E / tocopherol — cystic fibrosis or any exocrine pancreatic failure, abetalipoproteinemia: neuropathy + spinocerebellar ataxia + hemolysis; mimics B12 with normal B12",
          "Hypervitaminosis A — pseudotumor cerebri (headache, papilledema, young obese woman on isotretinoin or tetracycline), bone pain, hepatotoxicity",
          "Copper — after bariatric surgery or zinc excess (denture cream): a myelopathy identical to subacute combined degeneration with a normal B12",
        ],
      },
      {
        group: "Settings that trigger the search",
        items: [
          "Gastrectomy / bariatric surgery — confusion or Romberg soon after = THIAMINE (NBME loves B1 post-gastrectomy); spasticity years later = B12 (no intrinsic factor)",
          "Pernicious anemia — B12 deficiency plus another autoimmune disease (vitiligo, Hashimoto, type 1 DM): anti-intrinsic factor antibodies; lifelong IM B12",
          "Alcohol use disorder / alcoholism — thiamine, folate, niacin and B6 all fall; every confused or ataxic drinker gets IV thiamine before dextrose",
          "Exocrine pancreatic insufficiency / cystic fibrosis — fat-soluble A, D, E, K malabsorption: neuropathy = E, bowed tibias/low calcium = D, bleeding = K",
        ],
      },
      {
        group: "Findings",
        items: [
          "Confabulation / Korsakoff — retrograde + anterograde amnesia with invented memories after untreated Wernicke; mammillary body damage; largely irreversible",
          "Anterograde amnesia — the NBME answer for what giving thiamine to an intoxicated alcoholic most reduces the risk of",
          "Hypersegmented neutrophils / macrocytosis — B12 or folate; high methylmalonic acid is B12 only, homocysteine rises in both",
        ],
      },
    ],
    pearls:
      "Thiamine before glucose: dextrose without thiamine burns the last of it and precipitates Wernicke — the exam gives a hypoglycemic alcoholic and wants 'thiamine, then glucose'. Wernicke is a clinical diagnosis; do not wait for a level. B12 deficiency need not have neurologic signs, and neurologic signs need not have anemia — check B12 and methylmalonic acid in any unexplained neuropathy, dementia or myelopathy. Folate given alone to a B12-deficient patient fixes the blood and lets the cord degenerate. Nitrous oxide (whippets, anesthesia) inactivates B12 and gives a subacute combined degeneration with a normal level. Post-gastrectomy the exam's answer is thiamine if there is confusion or an early Romberg, B12 if the story is years of spasticity and proprioceptive loss. Copper deficiency is the mimic when B12 is normal after bariatric surgery.",
    reviewed: REVIEWED,
  },
  {
    id: "infection-toxic-nutrition-encephalopathy-causes",
    domain: "infection-toxic-nutrition",
    name: "Encephalopathy & delirium causes",
    org: NUTRITION,
    prompt: `62M with cirrhosis admitted after a variceal bleed is now somnolent with asterixis; ammonia 140. Separately, an 80F on the second night after hip surgery is agitated, inattentive and fluctuating; her list includes oxybutynin and diphenhydramine.\n\nName the metabolic, toxic, hyperthermic and vascular causes of encephalopathy with the first treatment step for each, then the workup of delirium in an elderly inpatient.`,
    keyPoints: [
      {
        group: "Metabolic",
        items: [
          "Hepatic encephalopathy — hyperammonemia after GI bleed, infection, constipation or sedatives; asterixis; LACTULOSE (acidifies gut → ammonium trapped) ± rifaximin/neomycin",
          "Uremic encephalopathy / uremia — renal failure with high BUN: confusion, asterixis, myoclonus, pericardial rub; dialysis",
          "Hypercalcemia — malignancy or hyperparathyroidism: stones, bones, groans, psychiatric overtones; NORMAL SALINE first, then a bisphosphonate; calcitonin only as a bridge, loops only once volume-replete",
          "Hyponatremia / hypernatremia — any sodium disturbance causes delirium; raise Na ≤8 mEq/L/24 h (osmotic demyelination), hypertonic saline only if seizing; lower Na ≤10–12/24 h (cerebral edema)",
          "Hypoglycemia — fingerstick first in every altered patient; dextrose (with thiamine in the malnourished); thyroid storm and myxedema are the other endocrine causes",
        ],
      },
      {
        group: "Toxic",
        items: [
          "Reye syndrome — aspirin in a child with influenza/varicella: vomiting, encephalopathy, hepatomegaly with microvesicular steatosis, high ammonia, normal bilirubin; supportive",
          "Lead poisoning — child in an old house with pica: irritability, colic, regression; microcytic anemia with basophilic stippling; encephalopathy → dimercaprol + EDTA, milder → succimer",
          "Alcohol withdrawal / delirium tremens — tremor 6–24 h, seizures 6–48 h, hallucinosis 12–48 h, DTs 48–96 h (tachycardia, fever, confusion); chlordiazepoxide (lorazepam if cirrhotic) + thiamine",
          "Anticholinergic drugs / diphenhydramine — elderly on oxybutynin, TCAs, antihistamines: dry, hot, retention, mydriasis; STOP the drug; benzos and opioids are the other culprits",
        ],
      },
      {
        group: "Hyperthermic & vascular",
        items: [
          "Serotonin syndrome — SSRI + MAOI/linezolid/tramadol/triptan within hours: CLONUS, hyperreflexia, diarrhea, mydriasis; stop the drugs, benzodiazepines, cyproheptadine",
          "Neuroleptic malignant syndrome / NMS — antipsychotic days–weeks: lead-pipe rigidity, fever, autonomic instability, CK very high; stop it, dantrolene or bromocriptine",
          "Hypertensive encephalopathy / PRES — BP >180/120 (vignettes say 220/120): headache, confusion, seizures, posterior white-matter edema; lower MAP ≤25% in the first hour (nicardipine, labetalol)",
        ],
      },
      {
        group: "Elderly delirium workup",
        items: [
          "Infection screen / urinalysis — occult UTI or pneumonia is the commonest precipitant; also CBC, BMP, LFTs, ammonia, TSH, cultures",
          "Medication review — Beers list: stop anticholinergics, benzodiazepines, opioids, sedative-hypnotics; check for withdrawal from home meds",
          "Non-contrast head CT — focal deficit, fall or anticoagulation (subdural), or no cause found after labs; add LP if febrile with no source",
        ],
      },
    ],
    pearls:
      "Delirium = acute, fluctuating inattention with a cause; dementia is the substrate, not the diagnosis. The first three moves in any altered patient: fingerstick glucose, thiamine if malnourished, naloxone if pinpoint pupils. Lactulose works by acidification — ammonia becomes ammonium, which the gut cannot absorb; titrate to 2–3 soft stools; neomycin/rifaximin kill the ammonia producers. Serotonin syndrome vs NMS: clonus and hyperreflexia with a fast onset vs lead-pipe rigidity and bradyreflexia over days; both get benzodiazepines and cooling, only NMS gets dantrolene. Reye: never aspirin under 18 with a viral illness (Kawasaki is the exception). Treat delirium non-pharmacologically first (reorient, sleep, glasses, hearing aids, family); low-dose haloperidol only for dangerous agitation, and never benzodiazepines unless it is alcohol or benzo withdrawal.",
    reviewed: REVIEWED,
  },
  // ─────────────────────────────── TOXINS ───────────────────────────────
  {
    id: "infection-toxic-nutrition-neurotoxins-drug-neurotoxicity",
    domain: "infection-toxic-nutrition",
    name: "Neurotoxins & drug neurotoxicity",
    org: TOXINS,
    prompt: `3-month-old with 2 days of constipation, poor suck, ptosis and a weak cry; the parents dipped the pacifier in honey. Separately, a 24M farm worker has drooling, miosis, wheeze, vomiting and muscle fasciculations after a day picking fruit.\n\nName the toxin or drug behind each syndrome with its mechanism or antidote, then the chemotherapy, antibiotic and eye/ear toxicities the exam tests.`,
    keyPoints: [
      {
        group: "Biological toxins",
        items: [
          "Botulism / botulinum toxin — cleaves SNARE → no ACh release: descending flaccid paralysis, dilated pupils, constipation; honey spores in infants, canned preformed toxin in adults; antitoxin",
          "Tetanus / tetanospasmin — cleaves SNARE in inhibitory interneurons → no GABA/glycine: trismus, risus sardonicus, opisthotonos; dirty umbilical stump or garden cut; TIG + vaccine + metronidazole",
          "Tetrodotoxin — pufferfish (fugu): BLOCKS sodium channels → perioral numbness then flaccid paralysis; supportive, ventilate",
          "Ciguatera — reef fish (barracuda, grouper): keeps sodium channels OPEN; GI symptoms then hot–cold temperature reversal and paresthesias; supportive",
        ],
      },
      {
        group: "Cholinergic & anticholinergic",
        items: [
          "Organophosphates — phosphorylate acetylcholinesterase: DUMBELS + fasciculations then paralysis; skin absorption (gloves prevent it); ATROPINE first, then pralidoxime before aging",
          "Anticholinergic / Jimson weed — Datura alkaloids, diphenhydramine, TCAs: hot, dry, red, blind, mad, retention; physostigmine (not if the QRS is wide from a TCA)",
        ],
      },
      {
        group: "Chemo & antibiotic neurotoxicity",
        items: [
          "Vincristine — binds tubulin, blocks microtubules: peripheral + autonomic 'toxic neuropathy', foot drop, constipation/ileus; dose-limiting",
          "Cisplatin — DNA crosslinker: sensory neuropathy AND ototoxicity (plus nephrotoxicity, hypomagnesemia); amifostine",
          "Aminoglycosides / gentamicin — CN VIII: sensorineural hearing loss and/or vertigo (the endocarditis patient whose room spins); nephrotoxic; loop diuretics add to it",
          "Isoniazid — depletes pyridoxine: neuropathy and seizures; INH-induced status epilepticus responds only to IV pyridoxine",
          "Metronidazole / nitroprusside — metronidazole: cerebellar ataxia, neuropathy with prolonged use; nitroprusside: cyanide → confusion + lactic acidosis; thiosulfate",
        ],
      },
      {
        group: "Eye & ear toxicity",
        items: [
          "Ethambutol — optic neuritis: blurred vision, central scotoma, red-green color loss; check acuity/color vision each visit; stop the drug",
          "Digoxin — Na/K-ATPase inhibitor: yellow-green halos ('van Gogh vision'), nausea, arrhythmia, hyperkalemia; digoxin Fab",
          "Sildenafil — PDE-5 inhibitor that also hits retinal PDE-6: blue-tinged haze (pilots grounded for hours after a dose); never with nitrates (hypotension)",
          "Quinidine / quinine — cinchonism: headache + tinnitus + flushing + vertigo; also QT prolongation",
          "Aspirin / salicylates — tinnitus is the first symptom of toxicity; respiratory alkalosis then anion-gap acidosis; alkalinize the urine, dialysis if severe",
        ],
      },
    ],
    pearls:
      "Botulinum vs tetanus: both cleave SNARE, one silences the excitatory ACh terminal (flaccid, descending, pupils dilated), the other silences inhibitory GABA/glycine interneurons (rigid, spasms). Botulinum toxin does not change the binding of exogenous ACh to its receptor — a favorite NBME mechanism trap — and the infant gets human botulism immune globulin (BabyBIG), the adult equine antitoxin. Organophosphates: atropine reverses only the muscarinic effects; pralidoxime regenerates the enzyme and treats the nicotinic weakness, but must be given before the phosphate bond ages. Tetrodotoxin blocks the sodium channel; ciguatera holds it open; both are supportive care. Ototoxicity can present as vertigo rather than deafness. Cinchonism = quinine/quinidine; tinnitus alone = aspirin; blue haze = sildenafil; yellow vision = digoxin; red-green loss = ethambutol.",
    reviewed: REVIEWED,
  },
];
