// src/data/neuroLocalizationDrills.ts
/**
 * Neurology drills — the "localization" domain (Cord & nerve localization) of
 * the Neurology drill bank.
 *
 * Each drill is one localizing question the shelf asks: which tract, which
 * cord syndrome, which spinal diagnosis (and whether to image), which root,
 * which leg or arm nerve, which cranial nerve. `org` splits the Browse list
 * into "Localization" (tracts, cord, roots, cranial nerves), "Differential"
 * (back & neck pain) and "Peripheral nerve" (limb nerves and entrapments).
 *
 * ITEM RULE — items are "<recall head> — <clue>"; only the head is graded
 * (gradableItem in drillProgressCore), so it is the shortest phrase a student
 * would actually write; "/" in a head lists alternative spellings any one of
 * which earns credit. Roots are written "L4 / knee reflex" so the bare level
 * credits and no two roots share a graded word. Cranial nerves are written
 * "Abducens / sixth nerve" because "CN VI" grades as the token "cn". Numbers,
 * cut-offs and nuance live after the dash or in pearls (never graded).
 *
 * Standard board values; educational use only.
 * GENERATED by the neuro drill workflow (2026-09-15) from a shelf-level
 * review (HY Neuro) plus standard neuroanatomy sources.
 */
import type { GuidelineDrill } from "./guidelineDrillBank";

const LOCALIZATION = "Localization";
const DIFFERENTIAL = "Differential";
const PERIPHERAL = "Peripheral nerve";
const REVIEWED = "2026-09-15";

export const NEURO_LOCALIZATION_DRILLS: GuidelineDrill[] = [
  // ───────────────────────── CORD: TRACTS & SYNDROMES ─────────────────────────
  {
    id: "localization-cord-tracts-umn-lmn",
    domain: "localization",
    name: "Spinal tracts & UMN vs LMN",
    org: LOCALIZATION,
    prompt: `31M stabbed in the back at T10. Exam: right leg weak with a brisk right knee jerk and an upgoing right plantar, right leg cannot feel vibration or joint position, and the LEFT leg cannot feel pinprick or cold from the umbilicus down.\n\nName each long tract with what it carries and where it crosses, then list the upper motor neuron signs, the lower motor neuron signs, and the bedside tests that localize a cord versus cerebellar versus root problem.`,
    keyPoints: [
      {
        group: "Tracts",
        items: [
          "Spinothalamic tract / anterolateral system — pain and temperature from the CONTRALATERAL body; crosses within 1–2 levels of entry at the anterior white commissure",
          "Corticospinal tract / lateral corticospinal — motor to the IPSILATERAL body below a cord lesion; already crossed at the medullary pyramids; UMN signs when cut",
          "Dorsal columns / dorsal column-medial lemniscus — vibration, proprioception and fine touch from the IPSILATERAL body; cross in the medulla; positive Romberg",
          "Anterior white commissure — the spinothalamic crossing; a central lesion (syrinx) takes pain/temperature BILATERALLY at that level with touch spared",
        ],
      },
      {
        group: "UMN signs (cortex to anterior horn)",
        items: [
          "Hyperreflexia — brisk reflexes with spread; the corticospinal tract normally dampens the reflex arc",
          "Babinski sign / upgoing plantar — extensor plantar response; normal only under ~1 year of age",
          "Clonus — rhythmic beats at the ankle on sustained dorsiflexion; sustained clonus is always pathologic",
          "Spasticity / hypertonia — velocity-dependent, clasp-knife; contrast with cogwheel/lead-pipe rigidity of basal ganglia",
        ],
      },
      {
        group: "LMN signs (anterior horn to muscle)",
        items: [
          "Fasciculations — visible twitches of denervated motor units; tongue fasciculations = bulbar LMN (ALS, SMA)",
          "Areflexia / hyporeflexia — the reflex arc itself is cut; also seen in neuropathy and Guillain-Barré",
          "Flaccidity / hypotonia / atrophy — hypotonia and early marked wasting; UMN wasting is late and from disuse only",
          "Anterior horn cell — the LMN cell body in the cord: polio, SMA, West Nile, and the LMN half of ALS; an anterior horn lesion is LMN, never UMN",
        ],
      },
      {
        group: "Bedside tests",
        items: [
          "Romberg — falls only when the eyes close = proprioception (dorsal columns or large-fiber neuropathy); cerebellar ataxia sways eyes open too",
          "Straight-leg raise — positive only if it REPRODUCES radiating leg pain (disc herniation); back pain alone on the test is nonspecific",
          "Sensory level — a dermatome below which every modality is lost = cord lesion at or above it; T4 nipple, T10 umbilicus",
        ],
      },
    ],
    pearls:
      "The crossing rule decides the side: pain/temperature crosses in the cord within 1–2 levels, so a cord hemisection loses it CONTRALATERALLY 1–2 levels below the lesion; motor and dorsal columns cross in the medulla, so they are lost IPSILATERALLY below any cord lesion. Above the medulla everything is contralateral, and crossed findings (face one side, body the other) mean brainstem. Acute cord injury is 'spinal shock': flaccid and areflexic for days to weeks before UMN signs appear, so early hyporeflexia does not exclude a cord lesion. Mixed UMN + LMN with no sensory loss is ALS; mixed with sensory loss is B12 (subacute combined degeneration) or cervical spondylotic myelopathy (LMN at the compressed level, UMN below). Hoffmann sign (flicking the middle finger flexes the thumb) is the cervical Babinski.",
    reviewed: REVIEWED,
  },
  {
    id: "localization-cord-syndromes",
    domain: "localization",
    name: "Spinal cord syndromes",
    org: LOCALIZATION,
    prompt: `27F with SLE develops, over 3 days, weakness of the left leg with brisk reflexes, loss of vibration sense in the left leg, and loss of pinprick on the right from the level of the costal margin down. MRI shows a T2-bright lesion at T7.\n\nName the cord syndromes by the tracts they take — selective tract loss, hemisection and vascular patterns, the terminal cord, and anterior horn disease — with the classic cause of each.`,
    keyPoints: [
      {
        group: "Selective tract loss",
        items: [
          "Tabes dorsalis — neurosyphilis takes the dorsal columns: lightning pains, sensory ataxia with Romberg positive, Argyll Robertson pupils, Charcot joints",
          "Syringomyelia / syrinx — central cavity at the anterior white commissure: cape-like bilateral pain/temperature loss with touch spared, hand wasting; Chiari I",
          "Subacute combined degeneration / B12 deficiency — dorsal columns + corticospinal: proprioceptive ataxia with UMN signs; pernicious anemia, gastrectomy, vegan, nitrous oxide",
          "ALS / amyotrophic lateral sclerosis — UMN + LMN with NO sensory loss: corticospinal tracts and anterior horns; 'motor neurons' is the answer; riluzole",
        ],
      },
      {
        group: "Hemisection & vascular",
        items: [
          "Brown-Sequard / hemisection — ipsilateral motor + vibration/position, contralateral pain/temperature 1–2 levels below; on NBME usually transverse myelitis, not a stab",
          "Anterior cord syndrome / anterior spinal artery — motor + pain/temperature lost, dorsal columns SPARED; aortic surgery or dissection, atherosclerosis",
          "Central cord syndrome — arms weaker than legs (hands worst) with variable sensory loss and bladder dysfunction; hyperextension whiplash of an older spondylotic neck",
          "Transverse myelitis — inflammation across a whole level over days: viral, SLE, MS, NMO; can present as Brown-Sequard; MRI cord + LP, then steroids",
        ],
      },
      {
        group: "Terminal cord",
        items: [
          "Conus medullaris — ACUTE, symmetric, perianal anesthesia with EARLY urinary retention and fecal incontinence, mild leg weakness; T12–L2",
          "Cauda equina — GRADUAL, asymmetric radicular leg pain and weakness, saddle anesthesia, LATE retention; disc herniation or metastases; emergent MRI and decompression",
          "Epidural cord compression / metastatic cord compression — back pain then bilateral leg weakness in a cancer patient: IV dexamethasone FIRST, then MRI whole spine",
          "Tethered cord — myelomeningocele child or post-surgical adult with progressive leg/bladder deficits; low-lying conus on MRI; a diagnosis of exclusion on the shelf",
        ],
      },
      {
        group: "Anterior horn",
        items: [
          "Poliomyelitis / polio — asymmetric flaccid paralysis after a febrile GI prodrome in the unvaccinated; CSF lymphocytic; no sensory loss",
          "Spinal muscular atrophy / Werdnig-Hoffmann / SMA — SMN1, autosomal recessive; floppy infant with tongue fasciculations and absent reflexes; nusinersen",
          "West Nile virus — summer mosquito-borne polio-like flaccid paralysis in an older adult, often with fever and encephalitis",
        ],
      },
    ],
    pearls:
      "Sort by modality first: pain/temperature alone = spinothalamic (syrinx if bilateral and cape-like), vibration/position alone = dorsal columns (tabes, B12 early), motor alone = anterior horn or ALS, everything on one side plus contralateral pain = hemisection. Central cord after a fall in an elderly person with a stiff neck is the most-tested trauma pattern; anterior cord after aortic repair is the most-tested vascular pattern (the artery of Adamkiewicz). Conus vs cauda: conus is cord (early sphincter loss, symmetric, brisk-ish reflexes possible), cauda is roots (late retention, asymmetric radicular pain, areflexia) — but both are surgical emergencies once retention appears; get a post-void residual and an MRI the same day. Cancer plus new back pain plus leg weakness: give dexamethasone before the MRI is even done.",
    reviewed: REVIEWED,
  },
  // ───────────────────────────── SPINE DIAGNOSES ─────────────────────────────
  {
    id: "localization-spine-mechanical",
    domain: "localization",
    name: "Back & neck pain diagnoses",
    org: DIFFERENTIAL,
    prompt: `46M lifted a heavy box yesterday; now low back pain shoots down the back of the right leg to the foot, and raising the straight right leg reproduces the shooting pain. Strength, sensation and reflexes are normal. Separately, a 68F with 25 years of rheumatoid arthritis has neck pain and tingling in both hands before an elective knee replacement.\n\nName the lumbar and cervical diagnoses from their positional or exam clue, the red-flag causes of back pain, and the correct next step for each (often no imaging at all).`,
    keyPoints: [
      {
        group: "Lumbar",
        items: [
          "Disc herniation / herniated nucleus pulposus — radiating leg pain (radiculopathy) after lifting or bending; positive straight-leg raise; cervical version = arm pain, 'C8 disc herniation'",
          "Lumbosacral strain / paraspinal strain — paraspinal spasm after lifting WITHOUT radiation; straight-leg raise negative; no x-ray",
          "Lumbar spinal stenosis / neurogenic claudication — >50, leg pain walking or standing, relieved leaning forward (shopping cart; downhill worse); pulses normal",
          "Spondylolisthesis — palpable 'step-off' of one vertebra on the next; adolescent athlete (pars defect) or degenerative in the elderly",
        ],
      },
      {
        group: "Cervical",
        items: [
          "Cervical spondylosis — >50 with neck pain and degenerative changes on imaging; can cause radiculopathy or myelopathy (UMN signs in the legs)",
          "Atlantoaxial subluxation — advanced RA (or Down syndrome): C1–C2 instability; flexion-extension films or CT before any intubation; MRI if paresthesias",
          "Cervical foraminal stenosis / C7-T1 foraminal stenosis — older woman cannot fasten buttons: hand intrinsic weakness + numb little finger; foramen, not canal",
        ],
      },
      {
        group: "Red-flag back pain",
        items: [
          "Epidural abscess — point vertebral tenderness + fever, IV drug use, endocarditis, diabetes or a recent spinal procedure; MRI with contrast, cultures, surgery",
          "Vertebral metastases / spinal metastases — point tenderness, night pain, weight loss, known breast/prostate/lung cancer; MRI; dexamethasone if any cord sign",
          "Compression fracture / vertebral compression fracture — osteoporotic older woman or chronic steroids, sudden pain after trivial load; x-ray; kyphosis",
          "Pott disease / spinal tuberculosis — chronic back pain with gibbus in an immigrant or HIV patient; vertebral body and disc destruction; MRI + biopsy",
        ],
      },
      {
        group: "Next step / treatment",
        items: [
          "No diagnostic studies / no imaging — strain or radiculopathy without weakness, numbness or red flags: no x-ray, no MRI for at least 6 weeks",
          "NSAIDs / light exercise as tolerated — return to activity; bed rest is the wrong answer; ibuprofen alone is listed as an answer",
          "Flexion-extension x-rays / cervical spine CT — RA patient before intubation, to find atlantoaxial subluxation",
          "IV dexamethasone — suspected malignant cord compression: steroids before the MRI, then radiation oncology or neurosurgery",
        ],
      },
    ],
    pearls:
      "Uncomplicated low back pain is a no-imaging diagnosis: x-ray and MRI only for a neurologic deficit, a red flag (age >50 with cancer history, fever, IV drugs, steroids/osteoporosis, trauma, weight loss, retention/saddle anesthesia) or pain past 6 weeks. Radiating pain alone is not a deficit. Neurogenic claudication is relieved by sitting or leaning forward and has normal pulses; vascular claudication is relieved by standing still and has absent pulses. Any RA patient headed for the OR needs cervical flexion-extension films — anesthesia hyperextends the neck. Point tenderness over one vertebra means abscess, fracture or metastasis until proven otherwise; fever is not required for an epidural abscess. Meralgia paresthetica (burning lateral thigh from lateral femoral cutaneous nerve entrapment: obesity, pregnancy, tight belts) is the spine mimic that needs no imaging.",
    reviewed: REVIEWED,
  },
  // ────────────────────────────── ROOTS ──────────────────────────────
  {
    id: "localization-radiculopathy-levels",
    domain: "localization",
    name: "Radiculopathy levels",
    org: LOCALIZATION,
    prompt: `52M with low back pain radiating to the lateral leg and the top of the foot after lifting. He cannot walk on his heels; knee and ankle jerks are intact. Separately, a 44F with neck pain has a lost triceps reflex and a numb middle finger.\n\nFor the lumbosacral and cervical roots give the reflex, the weak movement, the dermatome and the disc that herniates onto each, then the dermatome landmarks used to read a sensory level.`,
    keyPoints: [
      {
        group: "Lumbosacral roots",
        items: [
          "L4 / knee reflex — patellar reflex lost, weak knee extension (and some dorsiflexion); numb knee + medial leg down to the medial malleolus; L3–4 disc",
          "L5 / dorsiflexion — weak dorsiflexion and great-toe extension (cannot heel-walk), NO reflex lost; numb lateral leg + dorsum of foot; L4–5 disc, the most common",
          "S1 / ankle reflex — Achilles reflex lost, weak plantarflexion (cannot toe-walk); numb posterior leg + sole and lateral foot; L5–S1 disc; SALT",
        ],
      },
      {
        group: "Cervical roots",
        items: [
          "C5 / deltoid — shoulder abduction and elbow flexion; biceps reflex; numb lateral upper arm (the 'regimental badge')",
          "C6 / thumb — wrist extension; brachioradialis and biceps reflex; numb thumb + index finger; C5–6 disc; a burned thumb is C6",
          "C7 / middle finger — elbow extension and wrist flexion; triceps reflex; numb middle finger; C6–7 disc, the most common cervical level",
          "C8 / little finger — finger flexion; numb little finger + medial forearm; C7–T1 disc ('C8 disc herniation' on NBME)",
          "T1 / hand intrinsics — finger abduction; numb medial arm; Horner syndrome if the root is avulsed (Klumpke)",
        ],
      },
      {
        group: "Dermatome landmarks",
        items: [
          "T4 / nipple — 'T4 at the teat pore'; the sensory level of a mid-thoracic cord lesion",
          "T10 / umbilicus — 'belly but-TEN'; appendiceal referred pain",
          "L1 / inguinal ligament — 'L1 is IL'; genitofemoral and ilioinguinal territory",
          "S2-S4 / perianal — saddle area; erection, bladder and bowel ('S2, 3, 4 keep the pee off the floor')",
        ],
      },
    ],
    pearls:
      "The disc herniates posterolaterally and pinches the root that EXITS ONE LEVEL BELOW it: L4–5 disc → L5 root, L5–S1 disc → S1 root (in the neck the numbering is offset: C6–7 disc → C7 root, C7–T1 → C8). Reflex map: biceps C5–6, triceps C7, knee L4, ankle S1 — L5 has no reflex, which is how you tell L5 (foot drop with normal reflexes) from S1 (lost ankle jerk). Root versus nerve: an L5 radiculopathy weakens dorsiflexion AND inversion AND hip abduction with back pain, whereas a common peroneal palsy spares inversion (tibial) and has no back pain. Dermatomal numbness follows a stripe; peripheral nerve numbness follows a patch. A progressive or severe motor deficit, or any retention/saddle change, turns 'no imaging' into MRI now; a mild deficit or a lost reflex alone with pain still allows 4–6 weeks of conservative care before MRI.",
    reviewed: REVIEWED,
  },
  // ───────────────────────────── LIMB NERVES ─────────────────────────────
  {
    id: "localization-lower-limb-nerves",
    domain: "localization",
    name: "Lower limb nerve injuries",
    org: PERIPHERAL,
    prompt: `38M wakes after a long flight with the right foot slapping on the floor: he cannot dorsiflex or evert the foot, inversion and plantarflexion are normal, and the upper lateral shin is numb. Knee and ankle reflexes are intact and there is no back pain.\n\nName the peripheral nerve for each lost hip, knee or foot movement or patch of leg numbness, from the sciatic tree, the femoral/obturator group, the gluteal nerves, and the sensory-only nerves and entrapments.`,
    keyPoints: [
      {
        group: "Sciatic tree",
        items: [
          "Sciatic — tibial AND common peroneal lost together, or shooting pain down the leg; posterior hip dislocation, misplaced gluteal injection; hamstrings weak, knee jerk kept",
          "Common peroneal / common fibular — dorsiflexion AND eversion lost (foot drop), numb upper lateral leg; compressed at the fibular neck: casts, leg crossing, weight loss",
          "Superficial peroneal — eversion lost, dorsiflexion kept; numb lower lateral leg and dorsum of the foot",
          "Deep peroneal — dorsiflexion lost, eversion kept: high-steppage gait; numb first web space; anterior compartment syndrome",
          "Tibial — plantarflexion and inversion lost (cannot stand on tiptoe), numb sole; tarsal tunnel at the ankle; Baker cyst or knee dislocation",
        ],
      },
      {
        group: "Femoral & obturator",
        items: [
          "Femoral — knee extension lost, knee buckles, knee jerk lost; numb anterior thigh + medial leg; retroperitoneal/psoas hematoma, lithotomy position, pelvic surgery",
          "Obturator — hip adduction lost with numb medial thigh; pelvic surgery, obturator hernia (Howship-Romberg sign)",
        ],
      },
      {
        group: "Gluteal",
        items: [
          "Superior gluteal — gluteus medius/minimus: Trendelenburg gait (pelvis drops on the swing side, trunk leans TOWARD the lesion); lateral-approach hip surgery, injection in the upper INNER quadrant",
          "Inferior gluteal — gluteus maximus: cannot rise from a chair, climb stairs or push off; hip extension lost",
        ],
      },
      {
        group: "Sensory-only nerves & entrapments",
        items: [
          "Saphenous — numb MEDIAL calf; the sensory end of the femoral nerve; injured in vein stripping or knee surgery",
          "Sural — numb lower LATERAL calf; pure sensory, so it is the nerve harvested for a graft or biopsied",
          "Meralgia paresthetica — burning numb lateral thigh with no weakness: lateral femoral cutaneous nerve under the inguinal ligament; obesity, pregnancy, tight belts",
          "Diabetic amyotrophy / lumbosacral plexopathy — painful asymmetric proximal thigh weakness and wasting with weight loss in a type 2 diabetic; a plexus, not a nerve",
        ],
      },
    ],
    pearls:
      "Foot drop has three levels: L5 root (back pain, inversion also weak, hip abduction weak), common peroneal (fibular neck compression, inversion SPARED, no back pain — the answer in casts, crash diets and leg-crossers) and sciatic (plantarflexion also lost, hamstrings weak). Deep for Dorsiflexion, Superficial for eversion. suraL is Lateral, so saphenous is medial. Trendelenburg: the pelvis sags on the side OPPOSITE the weak gluteus medius and the patient lurches toward the weak side. Femoral nerve palsy with a groin/flank hematoma in an anticoagulated patient is a retroperitoneal bleed — CT, not nerve conduction. Charcot joint (disorganized tarsometatarsal joints on x-ray) is the diabetic foot that has lost pain sensation, not a nerve injury.",
    reviewed: REVIEWED,
  },
  {
    id: "localization-upper-limb-nerves",
    domain: "localization",
    name: "Upper limb nerve & plexus injuries",
    org: PERIPHERAL,
    prompt: `24M falls from a ladder and has a midshaft humeral fracture; the wrist hangs limp and he cannot extend the fingers. Separately, a 41F office worker has months of night-time tingling of the thumb, index and middle fingers that wakes her, with normal sensation over the back of the hand.\n\nName the nerve injured by each fracture site, the entrapment syndromes, the brachial plexus injuries, and the diagnostic step and first-line treatment the shelf wants for the entrapments (surgery is never first).`,
    keyPoints: [
      {
        group: "Fracture site to nerve",
        items: [
          "Axillary — surgical neck of humerus or anterior shoulder dislocation: flattened deltoid, weak abduction 15–90°, numb lateral upper arm",
          "Radial — midshaft humerus or radial groove ('Saturday night palsy'): wrist drop with pronated forearm, numb dorsal first web; BEST = brachioradialis, extensors, supinator, triceps",
          "Median — supracondylar humerus fracture: lost thumb opposition/abduction, thenar wasting ('ape hand'), hand of benediction on making a fist, numb lateral 3½ fingers",
          "Ulnar — medial epicondyle fracture: claw hand, Froment sign (thumb flexes when pinching paper), lost finger abduction/adduction, numb medial 1½ fingers",
        ],
      },
      {
        group: "Entrapment syndromes",
        items: [
          "Carpal tunnel — median at the wrist: night paresthesias of thumb/index/middle, weak thumb abduction, thenar wasting; thenar-eminence skin and back of hand SPARED; pregnancy, hypothyroidism, acromegaly",
          "Cubital tunnel — ulnar at the elbow: 'carpal tunnel on the ulnar side' — numb medial 1½ fingers PLUS the ulnar back of the hand, weak little-finger DIP flexion; worse flexing or leaning on the elbow",
          "Guyon canal — ulnar at the wrist only: numb 4th/5th fingers and hypothenar with the back of the hand SPARED (dorsal branch leaves above the wrist); hook of hamate fracture, cyclist handlebars",
          "Long thoracic — serratus anterior: winged scapula after mastectomy/axillary node dissection or a backpack strap; cannot raise the arm above the head",
        ],
      },
      {
        group: "Brachial plexus",
        items: [
          "Erb-Duchenne / upper trunk — C5–C6 traction (shoulder dystocia, fall on the shoulder): 'waiter's tip' — arm adducted, internally rotated, pronated, wrist flexed",
          "Klumpke / lower trunk — C8–T1 traction (breech, grabbing a branch while falling): claw hand with intrinsic wasting, ± Horner syndrome",
          "Thoracic outlet syndrome — lower trunk and subclavian vessels squeezed by a cervical rib or scalenes: hand intrinsic wasting, numb medial arm, symptoms with the arm overhead",
        ],
      },
      {
        group: "Diagnosis & treatment",
        items: [
          "EMG / nerve conduction studies / electrophysiologic testing — the 'next step in diagnosis' for carpal tunnel on the shelf; Tinel and Phalen are not enough",
          "Wrist splint / wrist pad — first-line for carpal tunnel: neutral night splint, ergonomic wrist pad at the keyboard",
          "Triamcinolone injection / steroid injection — carpal tunnel after the splint fails; NSAIDs are unproven; release surgery only for thenar wasting, axonal loss on NCS or failed injection",
          "Overnight elbow splint / elbow splint — cubital tunnel: keep the elbow straight at night, stop leaning on it; ulnar nerve transposition only if this fails",
        ],
      },
    ],
    pearls:
      "Humerus fracture map: surgical neck = axillary, midshaft = radial, supracondylar = median (and the brachial artery — check the radial pulse), medial epicondyle = ulnar. Median versus ulnar in the hand: the median does thumb OPPOSITION and abduction (touch the pinky), the ulnar does thumb ADDUCTION (Froment) and finger spreading. Claw hand is ulnar (or Klumpke); wrist drop is radial (or a lead or vasculitic mononeuritis multiplex — a Wegener vignette with wrist AND foot drop). Carpal tunnel spares the thenar-eminence skin (palmar cutaneous branch leaves before the tunnel) and the dorsum (radial); cubital tunnel adds the ulnar dorsum of the hand, Guyon canal spares it. Musculocutaneous injury = weak biceps + numb lateral forearm. Bilateral carpal tunnel in a jackhammer operator, or with acromegaly, hypothyroidism, amyloid or dialysis, is the shelf's 'secondary' carpal tunnel — treat the cause too.",
    reviewed: REVIEWED,
  },
  // ─────────────────────────── CRANIAL NERVES ───────────────────────────
  {
    id: "localization-cranial-nerves",
    domain: "localization",
    name: "Cranial nerve lesions",
    org: LOCALIZATION,
    prompt: `61F with diabetes has sudden double vision; the right eye rests down and out with a droopy lid, but the pupil is normal. Separately, a 34M has a week of drooping of the whole left face including the forehead, with hyperacusis and loss of taste.\n\nFrom an eye position, a facial or tongue finding, or a lost reflex, name the cranial nerve (with its exit foramen and the classic cause), separating the two facial palsies, and name the skull-base openings the shelf asks about.`,
    keyPoints: [
      {
        group: "Eye movement",
        items: [
          "Oculomotor / third nerve / CN III — down-and-out eye with ptosis; pupil BLOWN = compression (PCom aneurysm, uncal herniation), pupil SPARED = diabetic ischemia; Weber",
          "Trochlear / fourth nerve — superior oblique: vertical diplopia worst looking down and in (stairs, reading), head tilts AWAY from the lesion",
          "Abducens / sixth nerve — cannot abduct, eye rests medially; the long intracranial course makes it a false localizer of raised ICP; cavernous sinus, pontine stroke",
          "MLF / internuclear ophthalmoplegia / INO — adducting eye lags, abducting eye nystagmus, convergence preserved; MS in the young, stroke in the old",
        ],
      },
      {
        group: "Face, taste & hearing",
        items: [
          "LMN facial / Bell palsy / CN VII — whole hemiface INCLUDING forehead, hyperacusis, lost taste anterior two-thirds; idiopathic, Lyme, Ramsay Hunt (zoster); steroids",
          "UMN facial / central facial weakness — forehead SPARED, contralateral lower face; stroke or tumor in the contralateral motor cortex or internal capsule",
          "Trigeminal / fifth nerve — facial sensation, corneal reflex afferent (V1), mastication (V3); trigeminal neuralgia = lancinating seconds-long jolts on touch; carbamazepine",
          "Vestibulocochlear / eighth nerve / CN VIII — sensorineural loss + tinnitus + imbalance: vestibular schwannoma at the cerebellopontine angle (bilateral = NF2); MRI",
        ],
      },
      {
        group: "Lower cranial nerves",
        items: [
          "Glossopharyngeal / ninth nerve — gag reflex AFFERENT, carotid sinus baroreceptor, taste posterior third; exits the jugular foramen",
          "Vagus / tenth nerve — gag EFFERENT and palate: uvula deviates AWAY from the lesion; hoarseness (recurrent laryngeal); parasympathetic brake on heart rate (stimulation = bradycardia); jugular foramen",
          "Accessory / eleventh nerve / spinal accessory — sternocleidomastoid (turn head to the opposite side) and trapezius (shrug); injured in posterior-triangle node biopsy",
          "Hypoglossal / twelfth nerve / CN XII — tongue deviates TOWARD the lesion ('lick your wound') with ipsilateral wasting; hypoglossal canal; medial medullary stroke, foramen magnum tumor",
        ],
      },
      {
        group: "Skull-base openings",
        items: [
          "Superior orbital fissure — III, IV, V1, VI (plus the ophthalmic vein): a lesion there takes all eye movements and corneal sensation, sparing vision",
          "Jugular foramen — IX, X, XI: dysphagia, hoarseness, lost gag, weak shrug together (jugular foramen syndrome: glomus tumor, skull-base fracture)",
          "Cribriform plate / olfactory / first nerve — CN I; anterior skull-base fracture: anosmia (patients report 'lost taste') and CSF rhinorrhea; no facial weakness",
        ],
      },
    ],
    pearls:
      "Third nerve palsy is the one you must not miss: the parasympathetic pupil fibers run on the OUTSIDE of the nerve, so compression (posterior communicating aneurysm, uncal herniation) blows the pupil early and needs an emergent CTA, while diabetic microvascular ischemia hits the core and spares the pupil — observe. Forehead decides the facial palsy: forehead involved = peripheral (Bell), forehead spared = central (stroke) — and an isolated loss of taste or smell WITHOUT facial weakness is the olfactory nerve after head trauma. Uvula goes AWAY from a vagal lesion; tongue goes TOWARD a hypoglossal lesion. Trigeminal foramina: V1 superior orbital fissure, V2 rotundum, V3 ovale ('Standing Room Only'). Bell palsy: prednisone within 72 hours, eye lubrication and taping; add valacyclovir if vesicles in the ear canal (Ramsay Hunt); in an endemic area or with a rash, test for Lyme — bilateral facial palsy is Lyme, sarcoid or Guillain-Barré until proven otherwise.",
    reviewed: REVIEWED,
  },
];
