// src/data/neuroHemorrhageTraumaTumorDrills.ts
/**
 * Neurology drills — the "hemorrhage-trauma-tumor" domain (Hemorrhage, trauma & tumors) of the Neurology drill bank.
 * Items are "<recall head> — <clue>"; only the head is graded. See
 * neuroGuidelineDrills.ts for the domain and the conventions.
 *
 * Each drill is one exam-shaped decision: name the bleed from vessel + CT
 * shape, the herniation from its signs, the skull-base sign from its bruise,
 * the tumor from age + location + histology, the phakomatosis from its skin
 * and tumor pairing, the malformation from its embryology. `org` is
 * "Differential", "Management" or "Localization" so the Browse list splits
 * the families.
 *
 * ITEM RULE — heads are the shortest phrase a student would write; "/" in a
 * head lists alternative names any one of which earns credit. Two heads in
 * one drill never share their distinctive tokens (asserted in the test), so
 * e.g. Chiari II lives inside the myelomeningocele clue rather than as its
 * own head, and "CN VI" style alternatives are written out as nerve names.
 * Numbers, cut-offs and traps live after the dash or in pearls (never graded).
 *
 * GENERATED by the neuro drill workflow (2026-09-15); educational use only.
 */
import type { GuidelineDrill } from "./guidelineDrillBank";

const DIFFERENTIAL = "Differential";
const MANAGEMENT = "Management";
const LOCALIZATION = "Localization";
const REVIEWED = "2026-09-15";

export const NEURO_HEMORRHAGE_TRAUMA_TUMOR_DRILLS: GuidelineDrill[] = [
  // ───────────────────────── INTRACRANIAL BLEEDS ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-intracranial-bleeds",
    domain: "hemorrhage-trauma-tumor",
    name: "Intracranial bleed types",
    org: DIFFERENTIAL,
    prompt: `19M struck on the temple by a baseball, briefly unconscious, then walks and talks for 40 minutes before becoming drowsy with a dilated right pupil. Separately, a 74F on warfarin with two weeks of fluctuating confusion after a minor fall, and a 48F with 'the worst headache of my life' and a stiff neck.\n\nName each intracranial bleed with its source vessel and CT shape, the aneurysm/bleed risk factors a shelf expects, and the management steps in order.`,
    keyPoints: [
      {
        group: "Bleed, vessel & CT shape",
        items: [
          "Epidural hematoma / epidural — middle meningeal artery (pterion, temple blow); lucid interval then rapid decline; lens/biconvex, does not cross sutures",
          "Subdural hematoma / subdural — bridging veins; elderly, alcoholic, shaken baby, acceleration-deceleration; crescent that crosses sutures; mixed density if acute-on-chronic",
          "Subarachnoid hemorrhage / SAH — berry aneurysm (AcoM > PcoM); worst headache of life, meningismus, no focal deficit; 'star-fish' blood in the basal cisterns",
          "Intracerebral hemorrhage / ICH — Charcot-Bouchard microaneurysm of lenticulostriate arteries in chronic HTN; putamen; decorticate/decerebrate posturing = brainstem compression",
          "Pituitary apoplexy — hemorrhage into an adenoma or the postpartum pituitary; sudden headache + bitemporal hemianopsia + ophthalmoplegia; hydrocortisone first",
        ],
      },
      {
        group: "Aneurysm & bleed risk",
        items: [
          "Hypertension — the most common risk factor for berry aneurysm and the cause of Charcot-Bouchard ICH; an HTN patient still dies more often of MI than SAH",
          "ADPKD / polycystic kidney disease — berry aneurysms; screen with MRA when there is a family history of SAH",
          "Ehlers-Danlos — vascular type: berry aneurysm and arterial dissection; also Marfan, coarctation, fibromuscular dysplasia",
          "Posterior communicating aneurysm / PcoM — oculomotor palsy with a blown pupil (parasympathetics ride outside the nerve); AcoM is the most common site overall",
          "Cerebral amyloid angiopathy / amyloid — recurrent LOBAR bleeds in an elderly normotensive patient with Alzheimer; beta-amyloid in vessel walls",
        ],
      },
      {
        group: "Management",
        items: [
          "Noncontrast CT / CT head — first test for any suspected bleed; if negative but the SAH story is classic, LP for xanthochromia (or CTA)",
          "Intubation + hyperventilation / hyperventilation — GCS low or posturing: secure the airway, PaCO2 30–35 → vasoconstriction lowers ICP; then craniotomy",
          "Craniotomy / surgical evacuation — epidural and subdural: evacuate (NBME's answer even for subdural); after the airway if GCS is low",
          "Nimodipine — SAH: 21 days orally to prevent delayed vasospasm-ischemia (days 3–14); clip or coil the aneurysm early",
          "Reverse anticoagulation / FFP — warfarin: vitamin K + 4-factor PCC (FFP on NBME); dabigatran: idarucizumab; keep SBP ~140 in ICH",
        ],
      },
    ],
    pearls:
      "Lucid interval = epidural (arterial, fast); no lucid interval + slow decline = subdural (venous). Subdural is the answer for shaken baby (with retinal hemorrhages) and the confused elderly drinker weeks after a trivial fall. SAH mimics meningitis (stiff neck, photophobia) — the headache is thunderclap and noncontrast CT is nearly 100% sensitive within 6 h but falls to ~90% by 24 h; a negative CT does not end the workup. PcoM aneurysm = CN III palsy with a dilated pupil; a pupil-sparing CN III palsy is diabetic microvascular. ICH in a normotensive elderly patient in a lobar location = amyloid angiopathy; in a young cocaine user think sympathomimetic. Pituitary apoplexy: bitemporal hemianopsia right after delivery, only answer that fits. Small subdurals can be observed in real life, but on NBME the answer is craniotomy.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── RAISED ICP & HERNIATION ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-icp-herniation",
    domain: "hemorrhage-trauma-tumor",
    name: "Raised ICP & herniation syndromes",
    org: MANAGEMENT,
    prompt: `62M with a large left temporal hemorrhage becomes progressively somnolent. BP 190/100, HR 46, irregular breathing. Left pupil 7 mm and fixed, right arm and leg now weak.\n\nName the herniation syndromes by their signs, the signs of raised intracranial pressure, and the acute steps that lower ICP.`,
    keyPoints: [
      {
        group: "Herniation syndromes",
        items: [
          "Uncal herniation / uncal — medial temporal lobe over the tentorium: ipsilateral blown pupil (CN III), contralateral hemiparesis (peduncle); Kernohan notch = ipsilateral weakness",
          "Subfalcine / cingulate herniation — cingulate gyrus under the falx; compresses the ACA → contralateral leg weakness; often silent until late",
          "Central transtentorial — diencephalon pushed down through the tentorial notch: falling consciousness, bilateral motor signs, small then fixed pupils; Duret hemorrhages",
          "Tonsillar herniation / coning — cerebellar tonsils into the foramen magnum: medullary compression → respiratory and cardiac arrest; the LP-in-a-mass-lesion disaster",
          "Upward transtentorial — posterior fossa mass pushes the cerebellum up through the notch (classically after a ventricular drain); decreased consciousness, pupil changes",
        ],
      },
      {
        group: "Signs of raised ICP",
        items: [
          "Cushing reflex / Cushing triad — hypertension + bradycardia + irregular respirations; 'why is the trauma patient hypertensive' = increased intracranial pressure",
          "Papilledema — bilateral disc swelling, enlarged blind spot; takes days to develop, so its absence is not reassuring in acute herniation",
          "Morning headache and vomiting / morning vomiting — worse on waking, lying flat and with Valsalva; vomiting without nausea; the pediatric tumor tip-off",
          "Decorticate / decerebrate posturing — flexor (lesion above the red nucleus) vs extensor (below it, worse); either = low GCS and brainstem compromise",
          "Abducens palsy / CN VI palsy — false localizing sign from the long intracranial course of CN VI: horizontal diplopia, eye cannot abduct; any cause of raised ICP, including IIH",
        ],
      },
      {
        group: "Acute ICP management",
        items: [
          "Hyperventilation — PaCO2 30–35 mmHg → cerebral vasoconstriction; a bridge of minutes-hours to definitive treatment, not a fix; over-ventilating causes ischemia",
          "Mannitol / hypertonic saline — osmotic therapy; mannitol 0.25–1 g/kg (watch volume and kidneys); hypertonic saline preferred if hypotensive",
          "Dexamethasone / steroids — vasogenic edema around a tumor or abscess ONLY; harmful in TBI (CRASH) and useless in stroke or bleed",
          "CT before LP — focal deficit, papilledema, GCS <15, seizure or immunocompromise: an LP under a mass lesion precipitates tonsillar herniation",
          "Decompressive craniectomy / EVD — refractory ICP: craniectomy, or an external ventricular drain for hydrocephalus (also measures ICP); evacuate the mass",
        ],
      },
    ],
    pearls:
      "Uncal herniation is the exam favorite: ipsilateral fixed dilated pupil + contralateral hemiparesis in a deteriorating patient with a temporal mass. Kernohan notch is the trap — the contralateral peduncle is crushed against the tentorium, so weakness is on the same side as the mass. Monro-Kellie: skull volume is fixed, so blood, CSF or brain must give. Order of acute care: head of bed 30°, neutral neck, airway, hyperventilate briefly, osmotherapy, then surgery — and treat the pressure before the imaging finishes. Cushing reflex is late; do not chase the hypertension with antihypertensives. GCS is rarely calculated on NBME; posturing and 'GCS <15' are their code for 'CT before LP.' Steroids treat vasogenic (tumor) edema only — cytotoxic edema after trauma or stroke does not respond.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── HEAD TRAUMA ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-head-trauma",
    domain: "hemorrhage-trauma-tumor",
    name: "Head trauma syndromes",
    org: LOCALIZATION,
    prompt: `24M unrestrained driver in a high-speed collision, comatose at the scene with a nearly normal head CT. Separately, a 31F after a fall with bruising behind the ear, clear fluid dripping from the nose and blood behind the tympanic membrane.\n\nName the traumatic brain injury pattern from the mechanism, the skull-base fracture signs and the structure each localizes, and the deficits and complications that follow head injury.`,
    keyPoints: [
      {
        group: "Injury pattern",
        items: [
          "Diffuse axonal injury / DAI — high-speed deceleration/rotation shears axons: immediate coma with a near-normal CT; punctate grey-white junction hemorrhages on MRI; worst prognosis",
          "Concussion / post-concussion syndrome — transient dysfunction after a blow, ± brief LOC, normal CT; weeks-months of headache, poor concentration, photophobia, mood/sleep change",
          "Shaken baby / abusive head trauma — subdural + retinal hemorrhages + posterior rib or metaphyseal fractures in an infant with no story; mandated report",
          "Cerebral contusion / coup-contrecoup — bruised cortex at the frontal and temporal poles opposite the impact; 'blossoms' on the 24-hour repeat CT",
          "Chronic subdural hematoma — elderly or alcoholic weeks after a trivial fall: fluctuating confusion, headache, gait change; hypodense crescent",
        ],
      },
      {
        group: "Skull-base fracture signs",
        items: [
          "Battle sign — ecchymosis over the mastoid = petrous/posterior fossa fracture; appears 1–3 days after injury",
          "Raccoon eyes — bilateral periorbital ecchymosis = anterior fossa fracture",
          "CSF rhinorrhea / CSF otorrhea — clear fluid, halo sign on gauze, beta-2 transferrin positive; NO nasogastric tube (cribriform plate)",
          "Hemotympanum — blood behind the tympanic membrane = temporal bone fracture",
          "Anosmia / olfactory nerve — cribriform plate fracture shears CN I: loss of smell, food 'tastes bland'",
        ],
      },
      {
        group: "Sequelae",
        items: [
          "Facial nerve / facial palsy / CN VII — temporal bone fracture: LMN facial weakness ± sensorineural hearing loss; immediate onset suggests transection",
          "Frontal lobe / conceptual planning — orbitofrontal and dorsolateral contusion: disinhibition, apathy, impaired planning (NBME: 'conceptual planning')",
          "Cushing ulcer — head injury → vagal outflow → gastric acid hypersecretion → gastric/duodenal ulcer; PPI prophylaxis (Curling ulcer = burns)",
          "Post-traumatic epilepsy / seizure prophylaxis — levetiracetam or phenytoin for 7 days after severe TBI prevents EARLY seizures only",
          "Central diabetes insipidus — stalk/hypothalamic injury: polyuria and hypernatremia days after TBI; desmopressin",
        ],
      },
    ],
    pearls:
      "Coma with a clean CT after a high-speed crash is diffuse axonal injury — MRI shows the punctate hemorrhages the CT missed. Concussion: no same-day return to play, graded stepwise return; a second hit before recovery risks second-impact syndrome. Skull-base tetrad = Battle sign, raccoon eyes, CSF otorrhea, CSF rhinorrhea (plus hemotympanum); no nasogastric tube or nasal intubation, and prophylactic antibiotics do not prevent meningitis. Any head injury with neck pain, midline tenderness, intoxication or altered mentation gets a collar and CT of the cervical spine. Cushing reflex (ICP) and Cushing ulcer (vagal acid) share a name only. The frontal-lobe deficit NBME wants after a car accident is 'conceptual planning'.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── PEDIATRIC TUMORS ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-pediatric-tumors",
    domain: "hemorrhage-trauma-tumor",
    name: "Pediatric CNS tumors",
    org: DIFFERENTIAL,
    prompt: `4-year-old with three weeks of vomiting on waking, now unable to sit without swaying, with a wide-based gait. Fundi show blurred disc margins. MRI: a midline cerebellar mass filling the fourth ventricle.\n\nName the childhood CNS and neural tumors with the location, histology and embryology clue for each, and the presenting signs and workup that point to them.`,
    keyPoints: [
      {
        group: "Posterior fossa",
        items: [
          "Pilocytic astrocytoma — most common pediatric brain tumor; cerebellar hemisphere, cystic with a mural nodule; Rosenthal fibers, GFAP+; benign, cured by resection",
          "Medulloblastoma — vermis: truncal ataxia + morning vomiting; small round blue cells, Homer-Wright rosettes; 'drop metastases' down the CSF; radiosensitive",
          "Ependymoma — floor of the 4th ventricle → obstructive hydrocephalus; perivascular pseudorosettes; poor prognosis; spinal/NF2 in adults",
          "Brainstem glioma / diffuse pontine glioma — pons: cranial nerve palsies + long-tract signs + ataxia without early hydrocephalus; unresectable",
        ],
      },
      {
        group: "Supratentorial & sellar",
        items: [
          "Craniopharyngioma — Rathke pouch remnant (roof of the primitive oral cavity); calcified suprasellar cyst, 'motor oil' cholesterol crystals; bitemporal hemianopsia, growth failure, DI",
          "Pinealoma / germinoma — Parinaud syndrome, obstructive hydrocephalus, precocious puberty (hCG); germinoma is exquisitely radiosensitive",
          "Optic glioma / optic pathway glioma — NF1; painless proptosis and vision loss in a child; pilocytic histology",
          "Cortical tubers / SEGA — tuberous sclerosis: periventricular hamartomas and seizures (infantile spasms); subependymal giant cell astrocytoma at the foramen of Monro",
        ],
      },
      {
        group: "Neural crest & retina",
        items: [
          "Neuroblastoma — adrenal medulla or sympathetic chain: abdominal mass crossing the midline, HTN, opsoclonus-myoclonus 'dancing eyes'; urine HVA/VMA, N-myc",
          "Retinoblastoma — leukocoria (white pupil reflex), strabismus; RB1 on chromosome 13; hereditary form bilateral with later osteosarcoma",
        ],
      },
      {
        group: "Presentation & workup",
        items: [
          "Morning vomiting / morning headache — raised ICP from obstructive hydrocephalus; most pediatric tumors are infratentorial",
          "Truncal ataxia — midline vermis lesion (medulloblastoma); limb ataxia = cerebellar hemisphere (pilocytic), ipsilateral to the lesion",
          "Parinaud syndrome / upgaze palsy — dorsal midbrain compressed by a pineal mass: light-near dissociation, convergence-retraction nystagmus, lid retraction",
          "MRI brain / MRI — imaging of choice (the posterior fossa is poorly seen on CT); LP for CSF seeding only AFTER imaging",
          "Bitemporal hemianopsia — chiasm compression: craniopharyngioma in a child, pituitary adenoma in an adult",
        ],
      },
    ],
    pearls:
      "Kids' tumors are infratentorial (cerebellum, brainstem), adults' are supratentorial — so a child presents with hydrocephalus (morning vomiting, headache, papilledema) and ataxia rather than seizures. Truncal ataxia = vermis = medulloblastoma; a cystic hemisphere mass with a nodule = pilocytic astrocytoma, the benign one. Medulloblastoma and neuroblastoma both show Homer-Wright rosettes; retinoblastoma has Flexner-Wintersteiner rosettes. Craniopharyngioma is the child's bitemporal hemianopsia (Rathke pouch, calcified, recurs); prolactinoma is the adult's. Parinaud = pineal until proven otherwise. Neuroblastoma vs Wilms: neuroblastoma crosses the midline, calcifies, and comes with opsoclonus-myoclonus and catecholamine metabolites. Never LP a child with a posterior fossa mass before imaging.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── ADULT TUMORS ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-adult-tumors",
    domain: "hemorrhage-trauma-tumor",
    name: "Adult CNS tumors",
    org: DIFFERENTIAL,
    prompt: `58M with a first generalized seizure. MRI: an irregular ring-enhancing mass with central necrosis crossing the corpus callosum. Separately, a 44F with SLE on immunosuppressants and a single periventricular enhancing lesion, and a 50F with unilateral hearing loss and tinnitus.\n\nName the adult CNS tumors by location, imaging and histology, the metastatic presentations, and the first steps in workup and management.`,
    keyPoints: [
      {
        group: "Primary parenchymal",
        items: [
          "Glioblastoma / GBM — most common malignant primary adult brain tumor; grade IV astrocytoma; 'butterfly' across the corpus callosum, ring-enhancing with necrosis, pseudopalisading; ~15-month survival",
          "Oligodendroglioma — frontal lobe, slow, presents with seizures; 'fried egg' cells, 'chicken-wire' capillaries, calcifications; 1p/19q codeletion → chemosensitive",
          "Primary CNS lymphoma — immunosuppressed (AIDS CD4 <100 already on TMP-SMX, transplant, SLE); ring-enhancing/periventricular, EBV+, diffuse large B-cell; methotrexate",
        ],
      },
      {
        group: "Extra-axial & sellar",
        items: [
          "Meningioma — arachnoid cap cells; dural-based, 'sits on' the brain with a dural tail; psammoma bodies, whorls; women, progesterone receptors; parasagittal → leg weakness",
          "Vestibular schwannoma / acoustic neuroma — CN VIII at the cerebellopontine angle: unilateral sensorineural loss, tinnitus, imbalance; S-100+, Antoni A/B; bilateral = NF2",
          "Prolactinoma / pituitary adenoma — most common pituitary tumor; galactorrhea, amenorrhea or impotence, bitemporal hemianopsia; cabergoline/bromocriptine first, not surgery",
          "Foramen magnum tumor — usually a meningioma: ipsilateral hypoglossal palsy (tongue deviates toward the lesion), neck pain, spastic quadriparesis",
          "Colloid cyst — 3rd ventricle at the foramen of Monro; positional headache, drop attacks, sudden death from acute hydrocephalus",
        ],
      },
      {
        group: "Metastases",
        items: [
          "Brain metastases / grey-white junction — most common brain tumor overall: multiple round ring-enhancing lesions with edema; lung > breast > melanoma, renal, choriocarcinoma",
          "Epidural spinal cord compression / cord compression — back pain + bilateral leg weakness, sensory level, retention in a cancer patient: dexamethasone now, whole-spine MRI, radiation/surgery",
          "Leptomeningeal carcinomatosis — multiple cranial nerve palsies + radiculopathies + headache in a cancer patient; CSF cytology (may need 3 taps), enhancing meninges",
        ],
      },
      {
        group: "Workup & first steps",
        items: [
          "Seizure / first seizure — the presenting symptom of 30–50% of gliomas; every first adult seizure gets brain imaging",
          "MRI with gadolinium / MRI — imaging of choice; ring enhancement = GBM, lymphoma, metastasis, abscess or toxoplasma, so context decides",
          "Stereotactic biopsy / resection — tissue before therapy: maximal safe resection for GBM then temozolomide + radiation; lymphoma → biopsy then high-dose methotrexate, no resection",
          "Dexamethasone — vasogenic edema: relief within hours; HOLD if lymphoma is suspected until biopsy (steroids melt it and ruin the sample)",
        ],
      },
    ],
    pearls:
      "Ring-enhancing lesion in HIV: CD4 <100 and NOT on TMP-SMX → toxoplasma (treat empirically with sulfadiazine + pyrimethamine and re-image in 2 weeks); already on TMP-SMX prophylaxis, or an SLE/transplant patient → primary CNS lymphoma. GBM crossing the corpus callosum is the 'butterfly'; lymphoma also crosses but is homogeneous and periventricular. Meningioma is the benign, resectable one — parasagittal tumors mimic a spinal cord lesion with bilateral leg weakness. Unilateral sensorineural hearing loss with tinnitus is a vestibular schwannoma until MRI says otherwise; bilateral = NF2. Foramen magnum tumor and medial medullary syndrome are the two CN XII palsies NBME asks. Cord compression from metastasis: steroids first, then emergent MRI — do not wait for imaging to give dexamethasone.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── PHAKOMATOSES ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-phakomatoses",
    domain: "hemorrhage-trauma-tumor",
    name: "Phakomatoses",
    org: DIFFERENTIAL,
    prompt: `9-year-old with eight flat brown macules >5 mm, freckling in both axillae and brown spots on the iris; his father has dozens of soft skin nodules. Separately, a 26F with bilateral hearing loss and juvenile cataracts, and an infant with a facial port-wine stain and seizures.\n\nName the neurocutaneous syndromes with their gene or chromosome, the skin and eye clue that identifies each, and the tumor pairing each carries.`,
    keyPoints: [
      {
        group: "Syndrome & gene",
        items: [
          "NF1 / von Recklinghausen — AD, chromosome 17, neurofibromin (RAS-GAP); the most common phakomatosis; neurofibromas, scoliosis, learning problems",
          "NF2 / merlin — AD, chromosome 22 (merlin/schwannomin); bilateral vestibular schwannomas, meningiomas, ependymomas, juvenile cataracts",
          "Tuberous sclerosis — AD, TSC1 hamartin (chr 9) or TSC2 tuberin (chr 16); hamartomas everywhere; seizures/infantile spasms, autism",
          "Von Hippel-Lindau / VHL — AD, chromosome 3; loss of VHL leaves HIF constitutively active → hemangioblastomas, RCC, pheochromocytoma, pancreatic cysts",
          "Sturge-Weber — NOT inherited: somatic mosaic GNAQ; port-wine stain + leptomeningeal angioma + glaucoma; 'tram-track' gyral calcifications",
        ],
      },
      {
        group: "Skin & eye clues",
        items: [
          "Cafe-au-lait / Lisch nodules — ≥6 café-au-lait macules >5 mm prepubertal, axillary/inguinal freckling; Lisch = iris hamartomas → NF1",
          "Ash-leaf spots / shagreen patch / adenoma sebaceum — hypopigmented macules (Wood lamp), leathery lumbar plaque, facial angiofibromas, periungual fibromas → tuberous sclerosis",
          "Port-wine stain / nevus flammeus — V1 distribution, present at birth, does not fade; with glaucoma or seizures → Sturge-Weber",
          "Juvenile cataracts / posterior subcapsular cataract — bilateral cataracts in a child or young adult with a family history of deafness → NF2",
        ],
      },
      {
        group: "Tumor pairings",
        items: [
          "Optic glioma / pheochromocytoma — NF1: painless proptosis + vision loss; pheo with episodic HTN; also malignant peripheral nerve sheath tumor, juvenile myelomonocytic leukemia",
          "Vestibular schwannoma / acoustic neuroma — NF2 hallmark when bilateral: sensorineural hearing loss both sides in a young adult; plus meningiomas",
          "Cardiac rhabdomyoma / renal angiomyolipoma — tuberous sclerosis: rhabdomyoma in a fetus or infant (regresses), angiomyolipomas that bleed; SEGA in the ventricle",
          "Hemangioblastoma / clear cell RCC — VHL: cerebellar, retinal and spinal hemangioblastomas (EPO → polycythemia), bilateral clear-cell renal carcinoma",
          "Leptomeningeal angioma — Sturge-Weber: ipsilateral to the port-wine stain; seizures, contralateral hemiparesis, intellectual disability",
        ],
      },
    ],
    pearls:
      "Chromosomes: NF1 = 17 (17 letters in 'von Recklinghausen'), NF2 = 22 (type 2, two 2s); tuberous sclerosis 9/16, VHL 3. NF1 needs 2 of 7 criteria (café-au-lait, freckling, neurofibromas, Lisch nodules, optic glioma, bone dysplasia, first-degree relative). Tuberous sclerosis presents as infantile spasms with ash-leaf spots — vigabatrin is first-line for the spasms here; the cardiac rhabdomyoma is often found before birth and regresses. VHL: screen for pheo before any surgery, and the RCC is bilateral and multifocal. Sturge-Weber is sporadic (GNAQ), not autosomal dominant — a port-wine stain alone is common and benign; it is the V1 location plus glaucoma or seizures that makes the syndrome. Pheochromocytoma links NF1, VHL and MEN2.",
    reviewed: REVIEWED,
  },
  // ───────────────────────── CONGENITAL MALFORMATIONS ─────────────────────────
  {
    id: "hemorrhage-trauma-tumor-congenital-malformations",
    domain: "hemorrhage-trauma-tumor",
    name: "Congenital CNS malformations",
    org: DIFFERENTIAL,
    prompt: `Newborn with a fluid-filled sac over the lumbar spine, weak legs and a dribbling bladder; head circumference rising. Mother took valproate through the first trimester. Separately, a 17-year-old with occipital headaches on coughing and a cape-like loss of pain sensation across the shoulders.\n\nName the posterior fossa, neural tube and cortical malformations with the embryology and association for each, then the prevention and prenatal markers.`,
    keyPoints: [
      {
        group: "Posterior fossa",
        items: [
          "Chiari I / tonsillar ectopia — cerebellar tonsils >5 mm below the foramen magnum; teen or young adult with occipital headache on cough/Valsalva; syringomyelia (cape-like pain/temperature loss)",
          "Dandy-Walker — agenesis of the vermis + cystic dilation of the 4th ventricle with an enlarged posterior fossa; hydrocephalus, developmental delay",
        ],
      },
      {
        group: "Neural tube defects",
        items: [
          "Spina bifida occulta / spina bifida — bony arch fails to close, dura intact; tuft of hair or dimple over the lumbosacral spine; usually asymptomatic; normal AFP",
          "Meningocele — meninges herniate through the defect, cord stays in the canal; skin-covered sac, usually no deficit",
          "Myelomeningocele — cord + meninges in the sac: leg weakness, bowel/bladder loss; Chiari II (cerebellum + brainstem through the foramen magnum → dysphagia, stridor, hydrocephalus)",
          "Anencephaly — anterior neuropore fails to close: no forebrain or calvarium, polyhydramnios (no swallowing), very high AFP; incompatible with life",
          "Tethered cord — conus fixed by scar, lipoma or a repaired myelomeningocele: progressive leg weakness, back pain, incontinence as the child grows; diagnosis of exclusion",
        ],
      },
      {
        group: "Cortex & ventricles",
        items: [
          "Aqueductal stenosis — most common cause of congenital hydrocephalus: enlarging head, bulging fontanelle, sunset eyes; X-linked L1CAM or post-infectious",
          "Lissencephaly / double cortex — failed radial neuronal migration (LIS1, DCX): smooth brain or a band of heterotopic grey matter; severe epilepsy, delay",
          "Holoprosencephaly — forebrain fails to cleave (weeks 5–6): cyclopia, midline facial defects; SHH mutation, trisomy 13, fetal alcohol",
          "Fetal alcohol syndrome — smooth philtrum, thin upper lip, short palpebral fissures, microcephaly; the most common preventable cause of intellectual disability",
        ],
      },
      {
        group: "Prevention & prenatal markers",
        items: [
          "Folic acid — 400 µg daily from before conception (4 mg after a prior NTD); the neural tube closes by week 4, before most women know they are pregnant",
          "Valproate / carbamazepine — antiepileptics with the highest NTD risk (valproate ~1–2% spina bifida); true folate antagonists: methotrexate, trimethoprim; maternal diabetes and obesity",
          "Elevated maternal AFP / AFP — MSAFP at 16–18 weeks: high with open NTDs (and abdominal wall defects, wrong dates, twins), low with Down; normal in skin-covered defects",
          "Amniotic acetylcholinesterase — confirms an OPEN neural tube defect after a high AFP (with amniotic AFP); then targeted ultrasound",
        ],
      },
    ],
    pearls:
      "Neural tube closure is weeks 3–4 — folate must be on board before conception, and the standard dose is 400 µg (4 mg for a prior affected pregnancy). Open defects leak AFP and acetylcholinesterase into amniotic fluid; skin-covered ones (occulta, some meningoceles) do not raise AFP. Chiari I is the teenager with cough headache and a syrinx (tonsils only); Chiari II is the newborn with myelomeningocele, hydrocephalus and brainstem signs (cerebellum + brainstem). Dandy-Walker is the enlarged posterior fossa with no vermis. Tethered cord after myelomeningocele repair shows up years later as new leg weakness and incontinence — MRI shows a low-lying conus; it is a diagnosis of exclusion on the exam. Holoprosencephaly travels with trisomy 13 and SHH; fetal alcohol is the most common cause overall.",
    reviewed: REVIEWED,
  },
];
