// src/data/neuroDementiaMovementDrills.ts
/**
 * Neurology drills — the "dementia-movement" domain (Dementia & movement) of the
 * Neurology drill bank.
 *
 * Each drill is one presentation (cognitive decline, parkinsonism, a jerky
 * movement, unsteadiness, ventriculomegaly). The student lists the diagnoses
 * by family — degenerative vs vascular vs rapid, reversible vs not, plus vs
 * secondary, cerebellar vs sensory — with the clue that separates each, and
 * the test or first step that sorts them. `org` is "Differential", "Workup" or
 * "Localization" so the Browse list groups the drills by what they ask for.
 *
 * ITEM RULE — items are "<recall head> — <clue>". Only the head is graded
 * (gradableItem in drillProgressCore), so it is the shortest phrase a student
 * would actually write; "/" in a head lists alternative names any one of which
 * earns credit. Numbers, mechanisms and traps live after the dash or in
 * pearls, which are shown on reveal and never graded. Heads within one drill
 * must not credit each other — asserted in __tests__/neuroGuidelineDrills.test.ts
 * (that is why "Parkinson disease" is the given in the parkinsonism drill and
 * not an item: "parkinson" is a graded prefix of "parkinsonism").
 *
 * Standard board values; institutional protocols vary. Educational use only.
 * GENERATED by the neuro drill workflow (2026-09-15) from standard shelf sources.
 */
import type { GuidelineDrill } from "./guidelineDrillBank";

const DIFFERENTIAL = "Differential";
const WORKUP = "Workup";
const LOCALIZATION = "Localization";
const REVIEWED = "2026-09-15";

export const NEURO_DEMENTIA_MOVEMENT_DRILLS: GuidelineDrill[] = [
  // ───────────────────────────── DEMENTIA ─────────────────────────────
  {
    id: "dementia-movement-dementia-differential",
    domain: "dementia-movement",
    name: "Dementia by clue",
    org: DIFFERENTIAL,
    prompt: `74M with 2 years of progressive memory loss. Three patients sit beside him: a 68F who sees small children in the room and shuffles when she walks, a 58M whose family says he has become rude and apathetic and eats compulsively, and a 61M who has declined over 3 months and startles into jerks with every noise.\n\nList the dementias by family — neurodegenerative, vascular/structural, rapid/infectious — with the clue and pathology that separate each, then the Alzheimer-specific facts a shelf expects.`,
    keyPoints: [
      {
        group: "Neurodegenerative",
        items: [
          "Alzheimer disease — most common; gradual amnestic decline with a normal neuro exam, MMSE low 20s; β-amyloid plaques + hyperphosphorylated tau tangles; hippocampal atrophy",
          "Frontotemporal dementia / Pick disease — personality change, apathy, disinhibition, hyperorality BEFORE memory loss; onset <65; frontotemporal atrophy; silver-staining tau Pick bodies",
          "Lewy body dementia / DLB — dementia + visual hallucinations + parkinsonism within a year; fluctuating cognition, REM sleep behavior disorder; α-synuclein; antipsychotics worsen it",
          "Huntington disease — chorea + psychiatric change + dementia in the 30s–40s; AD CAG repeat on chromosome 4, anticipation; caudate atrophy",
        ],
      },
      {
        group: "Vascular / structural",
        items: [
          "Vascular dementia / multi-infarct — dementia + focal motor/sensory deficits (3/5 strength in one arm) in a hypertensive; stepwise decline; treat the risk factors",
          "Normal pressure hydrocephalus / NPH — wet, wobbly, wacky ± parkinsonism; magnetic gait comes first; ventricles enlarged out of proportion to atrophy; LP tap test, then shunt",
          "Subdural hematoma — elderly or alcoholic with falls or anticoagulants; fluctuating confusion, headache; crescent on CT; evacuate",
        ],
      },
      {
        group: "Rapid / infectious",
        items: [
          "Creutzfeldt-Jakob disease / CJD — decline over weeks to months + startle myoclonus; prion PrPSc β-sheet; 14-3-3 and RT-QuIC in CSF, periodic sharp waves on EEG; fatal within a year",
          "HIV-associated dementia / AIDS dementia complex — subcortical: slowed thinking, apathy, gait trouble; can mimic wet-wobbly-wacky; low CD4; antiretrovirals",
          "Progressive multifocal leukoencephalopathy / PML — JC virus REACTIVATION (not acute infection) with CD4 <200, natalizumab or rituximab; multifocal non-enhancing white-matter lesions",
          "Subacute sclerosing panencephalitis / SSPE — teenager years after measles: cognitive decline, myoclonus, periodic EEG; measles antibody in CSF",
        ],
      },
      {
        group: "Alzheimer specifics",
        items: [
          "Down syndrome / trisomy 21 — early-onset Alzheimer by the 40s: the amyloid precursor protein gene sits on chromosome 21",
          "Presenilin / APP — familial early-onset Alzheimer; presenilin is part of γ-secretase, which cleaves amyloid precursor protein",
          "Sundowning — nighttime worsening that resembles delirium; first step is to reduce ambient noise and distractions, not bright light all night",
          "Hydrocephalus ex vacuo — enlarged lateral ventricles from brain atrophy (Alzheimer, schizophrenia), not true hydrocephalus; nothing to shunt",
        ],
      },
    ],
    pearls:
      "The dementia question is 'what else is there besides memory loss?' Nothing else = Alzheimer (MMSE low 20s; ≥24 is the normal cutoff and the NBME gives 28+ for benign forgetfulness of aging). Hallucinations + parkinsonism = Lewy body — never haloperidol (severe rigidity), quetiapine if you must. Personality first = frontotemporal. Focal deficit in the stem = vascular. Weeks with myoclonus = CJD; without myoclonus it is a distractor. Gait first, then incontinence, then cognition = NPH, and the parkinsonism in the stem is a trap. Before naming any degeneration run the reversible screen (B12, TSH, RPR, depression, drugs, CT). Alzheimer treatment: donepezil/galantamine/rivastigmine (cholinesterase inhibitors), memantine (NMDA antagonist) for moderate–severe; neither changes the course.",
    reviewed: REVIEWED,
  },
  {
    id: "dementia-movement-reversible-dementia",
    domain: "dementia-movement",
    name: "Reversible cognitive decline",
    org: WORKUP,
    prompt: `81F brought by her daughter for 6 months of forgetfulness. She lives alone on tea and toast, answers in short quiet sentences, recalls 0/3 objects but finishes the clock face quickly when prompted. Takes diphenhydramine nightly for sleep. Reflexes relax slowly.\n\nList the reversible causes of cognitive decline by family — metabolic/nutritional, infectious, structural/psychiatric, drugs — with the clue and the test that identifies each.`,
    keyPoints: [
      {
        group: "Metabolic / nutritional",
        items: [
          "B12 deficiency / subacute combined degeneration — tea-and-toast, vegan, pernicious anemia, gastrectomy; macrocytosis, dorsal column + corticospinal signs; B12 and methylmalonic acid",
          "Thiamine deficiency / Wernicke-Korsakoff — alcoholic with confusion, ataxia, ophthalmoplegia, confabulation; thiamine BEFORE glucose",
          "Hypothyroidism — Hashimoto; slowed cognition, weight gain, cold intolerance, delayed reflex relaxation; TSH in every dementia workup",
          "Hypercalcemia — malignancy or hyperparathyroidism; confusion, constipation, polyuria, stones; calcium and PTH",
          "Hepatic encephalopathy / uremia — asterixis; ammonia in cirrhosis, BUN in renal failure; lactulose/rifaximin or dialysis",
        ],
      },
      {
        group: "Infectious / acute",
        items: [
          "Neurosyphilis — positive VDRL/RPR in an elderly patient with decline (NBME: 82F); confirm FTA-ABS, CSF VDRL; IV penicillin G",
          "Neuroborreliosis / Lyme — endemic area, dogs, hiking; facial palsy, radiculitis, cognitive slowing; serology, then ceftriaxone",
          "Delirium — acute, fluctuating inattention on top of any brain; UTI, pneumonia, new drug in the elderly; treat the cause, reorient",
        ],
      },
      {
        group: "Structural / psychiatric",
        items: [
          "Pseudodementia / depression — apathy, short quiet answers, 'I don't know', 0/3 recall yet completes tasks when prompted; screen for depression first; SSRI",
          "Normal pressure hydrocephalus / NPH — wet, wobbly, wacky; gait first; ventriculomegaly on CT; large-volume LP improves gait, then VP shunt",
          "Subdural hematoma / chronic subdural — falls, anticoagulants, alcohol; fluctuating headache and confusion; CT head is part of the workup",
        ],
      },
      {
        group: "Drugs",
        items: [
          "Anticholinergics / diphenhydramine — first-generation antihistamines, TCAs, oxybutynin; confusion + urinary retention in the elderly; Beers list, stop them",
          "Benzodiazepines / sedative-hypnotics — zolpidem and benzos; confusion, falls; taper rather than stop abruptly",
          "Carbidopa-levodopa — hallucinations or psychosis after a dose increase; DECREASE the dose, do not discontinue",
          "Opioids / alcohol — opioid sedation; alcohol adds Wernicke-Korsakoff and hepatic encephalopathy; ask and taper",
        ],
      },
    ],
    pearls:
      "The screen for every new dementia: CBC, B12, TSH, calcium, metabolic panel, RPR/HIV when risk, depression screen, medication review, and non-contrast CT or MRI. Pseudodementia is the trap answer: depressed patients say 'I don't know' rather than confabulate, perform badly on effortful tasks but can finish when pushed, and improve with an SSRI; Alzheimer patients minimize and guess. Delirium is inattention with a fluctuating course and is not dementia — find the infection, drug, or metabolic cause. B12 can be neurologically symptomatic with a normal MCV; methylmalonic acid confirms. After gastrectomy think thiamine if confusion, B12 if dorsal column signs. Anticholinergic burden is the most common iatrogenic cause in the elderly.",
    reviewed: REVIEWED,
  },
  // ───────────────────────────── MOVEMENT ─────────────────────────────
  {
    id: "dementia-movement-parkinsonism-tremor",
    domain: "dementia-movement",
    name: "Parkinsonism & tremor beyond Parkinson disease",
    org: DIFFERENTIAL,
    prompt: `Four patients: a 72M with rigidity, falls backward and cannot look down; a 66M with wet-wobbly-wacky plus a shuffling gait; a 24F with tremor, dystonia and abnormal LFTs; and a 45M whose hands shake when he holds a cup but steady after two beers.\n\nName the parkinsonian syndromes other than idiopathic Parkinson disease (Parkinson-plus and secondary), then the tremor types and the drug or withdrawal causes, each with the clue that separates it.`,
    keyPoints: [
      {
        group: "Parkinson-plus & mimics",
        items: [
          "Lewy body dementia / DLB — dementia within a year of parkinsonism, visual hallucinations, fluctuations, REM sleep behavior disorder; antipsychotic sensitivity",
          "Progressive supranuclear palsy / PSP — axial dystonia + parkinsonism, vertical (downward) gaze palsy, early falls backward; poor levodopa response",
          "Multiple system atrophy / Shy-Drager — parkinsonism + autonomic failure (orthostasis, urinary retention, impotence) ± cerebellar signs; poor levodopa response",
          "Normal pressure hydrocephalus / NPH — not a true plus syndrome: wet, wobbly, wacky + parkinsonism in an older man; magnetic gait; enlarged ventricles on CT; LP tap test, then shunt",
        ],
      },
      {
        group: "Secondary parkinsonism",
        items: [
          "Wilson disease / hepatolenticular degeneration — parkinsonism, tremor or dystonia under 40 = Wilson until proven otherwise; Kayser-Fleischer rings, low ceruloplasmin, liver disease",
          "MPTP — synthetic heroin contaminant that destroys the substantia nigra; acute parkinsonism in a young IV drug user",
          "Antipsychotics / metoclopramide — D2 blockade: haloperidol, risperidone, metoclopramide, prochlorperazine; symmetric onset; benztropine or stop the drug",
          "Vascular parkinsonism — lower-body, gait-predominant, stepwise, with stroke risk factors and white-matter disease; poor levodopa response",
        ],
      },
      {
        group: "Tremor types",
        items: [
          "Resting tremor — 4–6 Hz pill-rolling at rest, suppressed by action; Parkinson in the old, Wilson in the young",
          "Essential tremor — bilateral action/postural tremor of hands, head, voice; AD family history; improves with alcohol; propranolol or primidone",
          "Intention tremor — worsens as the hand approaches the target; cerebellar (MS, stroke, alcohol); with dysmetria",
          "Asterixis — negative myoclonus: 'hepatic flap' with the arms extended; hepatic encephalopathy, uremia, CO2 retention; not a true tremor",
        ],
      },
      {
        group: "Drug & withdrawal tremor",
        items: [
          "Lithium — fine tremor at therapeutic levels; coarse tremor + ataxia + confusion = toxicity; check the level, propranolol",
          "Valproate — tremor + abnormal LFTs: the NBME picks valproate over lithium when the liver tests are up (hepatotoxic, lithium is not)",
          "Albuterol / beta-agonist — fine tremor + tachycardia in an asthmatic after the inhaler",
          "Alcohol withdrawal / delirium tremens — tremor at 6–12 h, hallucinosis 12–24 h, seizures 24–48 h, DTs at 48–96 h; benzodiazepines",
        ],
      },
    ],
    pearls:
      "Idiopathic Parkinson disease: asymmetric resting tremor, bradykinesia, cogwheel rigidity, shuffling gait, micrographia; α-synuclein in the substantia nigra pars compacta; responds to levodopa — the plus syndromes do not. Red flags for a plus syndrome: symmetric onset, early falls, gaze palsy (PSP), early autonomic failure (MSA), early dementia or hallucinations (DLB). Young parkinsonism or any young movement disorder: slit-lamp for Kayser-Fleischer rings, ceruloplasmin, 24-h urine copper. Tremor timing names the system: rest = basal ganglia, action/postural = essential or physiologic (thyroid, caffeine, β-agonists, withdrawal), at the target = cerebellum. Essential tremor is the only tremor helped by alcohol; propranolol first, primidone if asthma or bradycardia. Drug-induced parkinsonism reverses over weeks to months after the D2 blocker stops.",
    reviewed: REVIEWED,
  },
  {
    id: "dementia-movement-chorea-hyperkinetic",
    domain: "dementia-movement",
    name: "Chorea, tics & hyperkinetic disorders",
    org: DIFFERENTIAL,
    prompt: `Three patients: a 9-year-old girl with jerky purposeless movements 4 weeks after a sore throat and a new heart murmur; a 67M diabetic whose right arm flings wildly since this morning; and a 71F on haloperidol for 8 years with lip-smacking and tongue-thrusting.\n\nName the hyperkinetic disorders — chorea/ballismus, tics, and the others — with the mechanism or trigger and the first-line management for each.`,
    keyPoints: [
      {
        group: "Chorea / ballismus",
        items: [
          "Huntington disease — AD CAG repeat on chromosome 4 with anticipation; chorea + psychiatric change + dementia in the 30s–40s; caudate atrophy; tetrabenazine for chorea",
          "Sydenham chorea — child weeks after group A strep / rheumatic fever; autoimmune antibodies against the basal ganglia; self-limited; penicillin prophylaxis",
          "Hemiballismus — wild flinging of one arm and leg; lacunar stroke of the CONTRALATERAL subthalamic nucleus in a diabetic hypertensive",
          "Tardive dyskinesia — months to years of D2 blockers (antipsychotics, metoclopramide); orofacial lip-smacking; stop or switch to clozapine, valbenazine",
          "Athetosis / choreoathetosis — slow writhing distal movements; cerebral palsy (kernicterus), Huntington",
        ],
      },
      {
        group: "Tics",
        items: [
          "Tourette syndrome — multiple motor + at least one vocal tic for >1 year, onset <18; comorbid OCD/ADHD; habit-reversal therapy, then α2-agonist or haloperidol/risperidone",
          "Provisional tic disorder — motor and/or vocal tics for <1 year in a child (often a single tic); low progression risk; reassure and follow up in 3–6 months",
          "PANDAS — new tics, OCD or ADHD weeks after strep pharyngitis; diagnose the etiology with anti-streptolysin O titers",
          "Stimulant-induced tics / methylphenidate — methylphenidate, amphetamines, caffeine unmask tics; reduce or switch the stimulant",
        ],
      },
      {
        group: "Other hyperkinetic",
        items: [
          "Myoclonus — brief shock-like jerks; CJD, juvenile myoclonic epilepsy (morning jerks, valproate), post-anoxic, uremia, serotonin syndrome",
          "Opsoclonus / dancing eyes — opsoclonus-myoclonus-ataxia; paraneoplastic neuroblastoma in a toddler (urine VMA/HVA), SCLC or breast in adults",
          "Restless legs syndrome / RLS — urge to move the legs at night, relieved by movement; check iron/ferritin first and replete; then gabapentin or ropinirole/pramipexole",
          "Dystonia / acute dystonic reaction — sustained twisting posture; torticollis or oculogyric crisis hours after haloperidol/metoclopramide; benztropine or diphenhydramine",
          "Akathisia — inner restlessness, pacing, cannot sit still, days to weeks after an antipsychotic; propranolol, lower the dose",
        ],
      },
    ],
    pearls:
      "Speed and shape name the movement: chorea is fast, jerky and purposeless; athetosis slow and writhing; ballismus violent and proximal; myoclonus a lightning jerk; tic a suppressible urge that builds and releases; dystonia a sustained posture. The antipsychotic timeline: acute dystonia in hours to days (benztropine), akathisia in days to weeks (propranolol), parkinsonism in weeks (benztropine, lower dose), tardive dyskinesia after months to years (switch to clozapine, valbenazine — anticholinergics make it worse). Sydenham chorea is a major Jones criterion on its own and can appear months after the pharyngitis. Restless legs: iron first, replete if ferritin <75; question banks link RLS to later Parkinson disease through the shared dopamine mechanism, though the evidence is weak. Huntington testing needs genetic counseling; the gene is diagnostic before symptoms.",
    reviewed: REVIEWED,
  },
  {
    id: "dementia-movement-ataxia",
    domain: "dementia-movement",
    name: "Ataxia & cerebellar signs",
    org: LOCALIZATION,
    prompt: `16M with 3 years of worsening unsteadiness, high-arched feet, kyphoscoliosis and a new systolic murmur; he sways with his eyes open and falls when they close. Separately, a 6-year-old with 2 weeks of morning vomiting who cannot sit without support.\n\nList the cerebellar signs and what each localizes, how to separate cerebellar from sensory ataxia, then the hereditary and acquired causes with the clue for each.`,
    keyPoints: [
      {
        group: "Cerebellar signs",
        items: [
          "Dysdiadochokinesia — impaired rapid alternating movements: cannot quickly pronate/supinate or tap",
          "Intention tremor / dysmetria — tremor worsens approaching the target; past-pointing on finger-nose and heel-shin",
          "Truncal ataxia / vermis — midline lesion: cannot sit or stand unsupported, wide-based gait; medulloblastoma in a child with morning vomiting",
          "Limb ataxia / cerebellar hemisphere — lateral lesion: IPSILATERAL dysmetria, dysdiadochokinesia, hypotonia — cerebellar signs are ipsilateral",
        ],
      },
      {
        group: "Cerebellar vs sensory",
        items: [
          "Romberg negative — cerebellar ataxia: sways with eyes open AND closed; proprioception is intact so closing the eyes adds nothing",
          "Romberg positive / sensory ataxia — steady with eyes open, falls when closed; dorsal columns (B12, tabes, neuropathy); lost vibration and proprioception",
          "Tabes dorsalis — tertiary syphilis: dorsal column loss, lightning pains, Argyll Robertson pupils, Charcot joints, positive Romberg",
        ],
      },
      {
        group: "Hereditary / congenital",
        items: [
          "Friedreich ataxia — AR GAA repeat (frataxin, chromosome 9); teen ataxia, kyphoscoliosis, pes cavus, hammer toes, hypertrophic cardiomyopathy (cause of death), diabetes",
          "Ataxia-telangiectasia — AR ATM gene: failure of double-stranded DNA break repair; ataxia by 2, ocular telangiectasias, IgA deficiency, lymphoma risk; high AFP",
          "Dandy-Walker malformation — cystic dilation of the 4th ventricle, absent cerebellar vermis, hydrocephalus; truncal ataxia and big head",
          "Chiari malformation — cerebellar tonsils below the foramen magnum; occipital headache with cough, syringomyelia (cape-like pain/temp loss); type II with myelomeningocele",
        ],
      },
      {
        group: "Acquired",
        items: [
          "Wernicke encephalopathy / thiamine — alcoholic: ataxia, confusion, ophthalmoplegia (A COW); mammillary bodies; give thiamine before glucose",
          "Medulloblastoma — child with morning headache and vomiting, papilledema, truncal ataxia; midline vermis mass fills the 4th ventricle; drop metastases",
          "Alcoholic cerebellar degeneration / alcohol — chronic alcohol atrophies the anterior vermis: gait and truncal ataxia with relatively spared arms",
          "Vitamin E deficiency — fat malabsorption (cystic fibrosis, cholestasis, abetalipoproteinemia): ataxia, neuropathy, retinopathy; mimics Friedreich",
        ],
      },
    ],
    pearls:
      "Romberg is a test of proprioception, not the cerebellum: it needs a patient who can stand with eyes open, so a cerebellar patient who sways either way is Romberg negative. Cerebellar lesions are ipsilateral — the crossing happens twice (cerebellum to red nucleus/thalamus, then cortex to cord). Midline = vermis = trunk and gait; lateral = hemisphere = limbs. Friedreich is the ataxia + cardiomyopathy answer; ataxia-telangiectasia the ataxia + recurrent sinopulmonary infections + telangiectasia answer; vitamin E the ataxia + cystic fibrosis answer. Acute ataxia in a child: post-varicella cerebellitis or drug ingestion; with opsoclonus think neuroblastoma. Sudden ataxia with vertigo and vomiting in an adult: cerebellar stroke or hemorrhage — CT now, it swells and herniates.",
    reviewed: REVIEWED,
  },
  {
    id: "dementia-movement-hydrocephalus",
    domain: "dementia-movement",
    name: "Hydrocephalus & raised CSF pressure",
    org: DIFFERENTIAL,
    prompt: `Three patients: a 3-week-old with a bulging fontanelle and enlarged lateral and third ventricles with a normal fourth; a 70M with gait apraxia, urgency and forgetfulness whose ventricles are large but whose opening pressure is normal; and a 26F with BMI 38, daily headache, pulsatile tinnitus and papilledema with a normal MRI.\n\nName the hydrocephalus types, the obstructive causes, idiopathic intracranial hypertension with its triggers and treatment, and the mechanisms the NBME asks about.`,
    keyPoints: [
      {
        group: "Types",
        items: [
          "Communicating hydrocephalus — CSF reaches the subarachnoid space but is not reabsorbed: arachnoid granulations scarred after meningitis or SAH; all ventricles enlarged",
          "Obstructive hydrocephalus — block within the ventricular system: aqueductal stenosis, colloid cyst, posterior fossa mass; only ventricles proximal to the block dilate; NBME also counts cord tumor",
          "Normal pressure hydrocephalus / NPH — wet, wobbly, wacky ± parkinsonism; normal opening pressure; ventricles enlarged out of proportion to atrophy; tap test, then VP shunt",
          "Hydrocephalus ex vacuo — ventriculomegaly from brain atrophy (Alzheimer, schizophrenia, HIV); pressure normal, no treatment",
        ],
      },
      {
        group: "Obstructive causes",
        items: [
          "Aqueductal stenosis — most common congenital hydrocephalus; narrowed aqueduct of Sylvius between the 3rd and 4th ventricles: lateral + 3rd dilate, 4th stays normal",
          "Colloid cyst — benign cyst at the anterior roof of the 3rd ventricle blocking the foramen of Monro; positional headaches, sudden death",
          "Posterior fossa tumor / medulloblastoma — 4th-ventricle compression in a child: morning headache and vomiting, papilledema, truncal ataxia",
          "Congenital toxoplasmosis — hydrocephalus + chorioretinitis + diffuse intracranial calcifications (CMV calcifications are periventricular)",
        ],
      },
      {
        group: "Idiopathic intracranial hypertension",
        items: [
          "Idiopathic intracranial hypertension / pseudotumor cerebri — obese young woman: daily headache, papilledema, pulsatile tinnitus, CN VI palsy; normal MRI, opening pressure >25 cm H2O",
          "Vitamin A / isotretinoin / tetracyclines — drug triggers; also growth hormone, OCPs, danazol, steroid withdrawal; stop the drug",
          "Acetazolamide — first-line (carbonic anhydrase inhibitor lowers CSF production) with weight loss; topiramate; optic nerve sheath fenestration or shunt if vision is threatened",
        ],
      },
      {
        group: "Mechanisms",
        items: [
          "Corona radiata impingement — NPH: stretched periventricular white matter; the leg and bladder fibers run nearest the ventricles, so gait goes first",
          "Failure to inhibit the voiding reflex — the NBME mechanism of NPH incontinence: frontal micturition control is disconnected",
          "Arachnoid granulation failure / impaired CSF reabsorption — the mechanism of communicating hydrocephalus after meningitis or subarachnoid blood",
          "Absent venous pulsations / papilledema — fundoscopic signs of raised ICP: lost spontaneous venous pulsations, blurred disc margins; CN VI palsy is a false localizing sign",
        ],
      },
    ],
    pearls:
      "Which ventricles are big tells you where the block is: all four = communicating (or ex vacuo, when the sulci are wide too); lateral + third with a normal fourth = aqueductal stenosis; lateral only = foramen of Monro (colloid cyst). NPH is the only 'hydrocephalus' with a normal opening pressure, and the shunt reverses gait far better than cognition — the tap test predicts who benefits. IIH: the danger is permanent vision loss from papilledema, so follow visual fields, not headache; LP is both diagnostic (high opening pressure, normal CSF) and briefly therapeutic. Never LP a patient with obstructive hydrocephalus or a posterior fossa mass — herniation. Congenital hydrocephalus in a newborn with chorioretinitis and scattered calcifications is toxoplasmosis; periventricular calcifications with microcephaly is CMV.",
    reviewed: REVIEWED,
  },
];
