// src/data/neuroHeadacheVertigoSeizureDrills.ts
/**
 * Neurology drills — the "headache-vertigo-seizure" domain (Headache, vertigo & seizures) of the Neurology drill bank.
 * Items are "<recall head> — <clue>"; only the head is graded. See
 * neuroGuidelineDrills.ts for the domain and the conventions.
 *
 * Six drills: headache by clue, headache treatment & prophylaxis, vertigo &
 * hearing loss, seizure classification & first-line drugs, pediatric epilepsy
 * syndromes, and status epilepticus with the seizure mimics. `org` is
 * "Differential", "Pharm" or "Management" so the Browse list groups the
 * name-the-diagnosis drills apart from the name-the-drug/next-step drills.
 *
 * ITEM RULE — "/" in a head lists alternative spellings any one of which earns
 * credit; numbers, cut-offs and nuance live after the dash or in pearls (shown
 * on reveal, never graded). Heads within one drill must not credit each other —
 * asserted in __tests__/neuroGuidelineDrills.test.ts. Two blueprint heads were
 * dropped for that reason: "atonic" is one typo away from "tonic" to the
 * grader, and a second spike-and-wave EEG head (Lennox-Gastaut's slow
 * spike-wave) grades identically to the 3-Hz one — both live in clues/pearls.
 *
 * Standard board values (NBME/shelf-level facts); institutional protocols
 * vary. Educational use only.
 * GENERATED by the neuro drill workflow (2026-09-15); educational use only.
 */
import type { GuidelineDrill } from "./guidelineDrillBank";

const DIFFERENTIAL = "Differential";
const PHARM = "Pharm";
const MANAGEMENT = "Management";
const REVIEWED = "2026-09-15";

export const NEURO_HEADACHE_VERTIGO_SEIZURE_DRILLS: GuidelineDrill[] = [
  // ───────────────────────────── HEADACHE ─────────────────────────────
  {
    id: "headache-vertigo-seizure-headache-types",
    domain: "headache-vertigo-seizure",
    name: "Headache by clue",
    org: DIFFERENTIAL,
    prompt: `Four patients with headache: a 28F with 6 hours of unilateral throbbing pain, nausea and photophobia after a zigzag visual disturbance; a 34M woken at 2 AM by 30 minutes of stabbing pain behind one eye with a tearing, red eye; a 68F with 3 weeks of temporal headache, pain on chewing and an ESR of 88; and a 41M with the worst headache of his life and a stiff neck.\n\nName the primary headaches, the neuralgias and facial-pain mimics, and the dangerous secondary causes, each with the clue that separates it.`,
    keyPoints: [
      {
        group: "Primary headache",
        items: [
          "Migraine — unilateral, throbbing, 4–72 h, nausea, photo/phonophobia, ± visual aura; young woman; NSAID then triptan",
          "Tension-type / tension headache — bilateral, dull, band-like, no nausea, relieved by sleep and acetaminophen; stress",
          "Cluster headache / cluster — male 20s–40s, wakes from sleep, 15–180 min behind one eye, lacrimation, rhinorrhea, miosis; paces the room; recurs nightly for weeks",
          "Medication-overuse headache / rebound headache — near-daily headache in someone using analgesics or triptans >10–15 days a month; withdraw the drug",
        ],
      },
      {
        group: "Neuralgia & facial-pain mimics",
        items: [
          "Trigeminal neuralgia — seconds of lancinating V2/V3 (or V1) pain triggered by brushing teeth, chewing, a gust of wind; CN V exits the pons; carbamazepine",
          "Postherpetic neuralgia / post-herpetic — burning pain persisting in a healed shingles dermatome; gabapentin or a TCA",
          "Temporomandibular joint / TMJ — jaw pain with chewing, clicking, tender joint, NORMAL ESR; the decoy for jaw claudication",
        ],
      },
      {
        group: "Secondary & dangerous",
        items: [
          "Temporal arteritis / giant cell arteritis — >50, unilateral temporal headache, jaw claudication, high ESR, ± polymyalgia rheumatica; steroids before biopsy",
          "Subarachnoid hemorrhage / SAH — thunderclap 'worst ever', stiff neck, ± brief LOC; non-contrast CT, LP for xanthochromia if CT negative; nimodipine",
          "Pseudotumor cerebri / idiopathic intracranial hypertension — obese young woman, papilledema, absent venous pulsations; OCPs, vitamin A, isotretinoin, tetracyclines",
          "Hypertensive encephalopathy — BP ~220/120 with headache, confusion, papilledema; IV nicardipine, labetalol or nitroprusside, MAP down ≤25% in hour one (confusion on nitroprusside = cyanide)",
          "Cavernous sinus thrombosis — headache, proptosis, ophthalmoplegia (CN VI first) after a facial or sinus infection; S. aureus; IV antibiotics + heparin",
        ],
      },
    ],
    pearls:
      "Red flags that turn a headache into an emergency: thunderclap onset, over 50 with jaw claudication or scalp tenderness, papilledema, fever with stiff neck (meningitis — blood cultures, antibiotics, then LP), new focal deficit, headache that wakes from sleep or worsens lying down/with Valsalva (mass), and headache in pregnancy or the puerperium (preeclampsia, venous sinus thrombosis). Cluster vs trigeminal neuralgia when both hit V1: cluster lasts 15 minutes to 3 hours with autonomic signs and wakes a young man from sleep; trigeminal neuralgia lasts seconds and is triggered by touch. Jaw pain + headache + normal ESR = TMJ; high ESR = temporal arteritis. Pseudotumor: LP shows high opening pressure with normal CSF — acetazolamide, weight loss, stop the offending drug, and watch vision (optic nerve sheath fenestration or shunt if it fails). SAH: a negative CT still needs an LP.",
    reviewed: REVIEWED,
  },
  {
    id: "headache-vertigo-seizure-headache-management",
    domain: "headache-vertigo-seizure",
    name: "Headache treatment & prophylaxis",
    org: PHARM,
    prompt: `31F with hypertension has 3 migraines a month, each aborted with ibuprofen and sumatriptan; she is 8 weeks pregnant and asks what to take now. Her brother has cluster headaches; her mother, 71, has temporal headache with jaw claudication and an ESR of 95.\n\nName the abortive agent and the prophylactic agent for each primary headache type and trigeminal neuralgia, the special-situation rules, and the steps for temporal arteritis.`,
    keyPoints: [
      {
        group: "Abortive",
        items: [
          "NSAID / ibuprofen — migraine step one; also aspirin or acetaminophen-aspirin-caffeine for mild attacks",
          "Sumatriptan / triptan — migraine step two if NSAIDs fail; 5-HT1B/1D agonist; contraindicated in CAD, prior stroke, uncontrolled HTN; NEVER prophylaxis",
          "High-flow oxygen / 100% oxygen — cluster abortive (12–15 L/min by non-rebreather); subcutaneous sumatriptan is the alternative",
          "Acetaminophen + rest — tension-type: sleep, acetaminophen or NSAID, taper caffeine",
          "Self-limiting / no abortive therapy — trigeminal neuralgia attacks last seconds, so only prophylaxis matters",
        ],
      },
      {
        group: "Prophylaxis",
        items: [
          "Propranolol / beta-blocker — migraine prophylaxis; the one answer for hypertension + migraine; avoid in asthma; topiramate, amitriptyline, valproate are the alternatives",
          "Verapamil — cluster prophylaxis (non-dihydropyridine CCB); prednisone bridge while it takes effect",
          "Carbamazepine — trigeminal neuralgia prophylaxis (sodium channel blocker); SIADH, aplastic anemia, neural tube defects; HLA-B*15:02 SJS",
          "Caffeine taper / amitriptyline — tension-type: taper caffeine and analgesics; amitriptyline if chronic (≥15 days a month)",
        ],
      },
      {
        group: "Special situations",
        items: [
          "Acetaminophen in pregnancy — the abortive for a pregnant migraineur previously on sumatriptan (NBME); no NSAIDs after 20 weeks (oligohydramnios, ductus closure), no ergots ever",
          "No estrogen contraceptives / avoid combined OCP — migraine WITH aura: estrogen raises stroke risk; progestin-only, IUD or barrier instead",
          "Withdraw the overused analgesic / medication overuse — analgesics or triptans >10–15 days a month cause daily headache; stop them, bridge with prophylaxis",
        ],
      },
      {
        group: "Temporal arteritis",
        items: [
          "IV methylprednisolone / steroids first — start on clinical suspicion, before and regardless of biopsy: prednisone 40–60 mg/day, IV methylprednisolone if vision is threatened",
          "Temporal artery biopsy — the next diagnostic step; within days of starting steroids; long segment because of skip lesions",
          "Ischemic optic neuropathy / blindness — the complication steroids prevent (NBME answer); irreversible once it happens",
        ],
      },
    ],
    pearls:
      "Triptans are abortive only — an NBME favorite is the patient taking sumatriptan daily 'for prevention', which is medication overuse. Triptans and ergots are vasoconstrictors: no CAD, no Prinzmetal, no hemiplegic or basilar migraine; ergots are contraindicated in pregnancy and triptans avoided there (acetaminophen is the NBME answer). Migraine with aura + estrogen = stroke risk, so combined OCPs are contraindicated. Prophylaxis is offered at ≥4 headache days a month: propranolol (or timolol), topiramate (weight loss, kidney stones, paresthesias), amitriptyline (if insomnia/depression), valproate (teratogenic), and CGRP monoclonal antibodies (erenumab) for refractory cases. Temporal arteritis: 'IV methylprednisolone now, biopsy within a week' — steroids do not change the biopsy for at least 1–2 weeks. If the question asks for the DIAGNOSTIC step, the answer is biopsy, not steroids.",
    reviewed: REVIEWED,
  },
  // ─────────────────────────── VERTIGO & HEARING ───────────────────────────
  {
    id: "headache-vertigo-seizure-vertigo-hearing",
    domain: "headache-vertigo-seizure",
    name: "Vertigo & hearing loss",
    org: DIFFERENTIAL,
    prompt: `55F with 3 months of 30-second spinning spells when she rolls over in bed; head hanging off the exam table with the head turned right produces rotary nystagmus. Separately, a 25M on gentamicin for endocarditis says the room is spinning, and a 32M has years of hour-long spinning spells with ear fullness, waxing-and-waning tinnitus and muffled low tones in one ear.\n\nName the peripheral and central causes of vertigo, the ototoxic drugs, and the hearing-loss patterns with their tuning-fork findings, each with its clue and the bedside test or maneuver.`,
    keyPoints: [
      {
        group: "Peripheral vertigo",
        items: [
          "BPPV / benign paroxysmal positional vertigo — seconds of spinning with head turns, no hearing loss; posterior canal otolith; Dix-Hallpike diagnoses, Epley treats",
          "Vestibular neuritis — days of constant vertigo and vomiting after a viral illness, NO hearing loss; unidirectional nystagmus; self-resolves, meclizine short-term",
          "Labyrinthitis — viral vertigo PLUS tinnitus or hearing loss (cochlea involved); NBME may write 'abnormal tympanic light reflex'; the answer when neuritis is not listed",
          "Meniere disease — episodic vertigo (20 min–hours) + fluctuating LOW-frequency hearing loss + tinnitus/fullness over years; endolymphatic hydrops; salt restriction, diuretics",
        ],
      },
      {
        group: "Central & structural",
        items: [
          "Vestibular schwannoma / acoustic neuroma — gradual unilateral sensorineural loss + tinnitus ± imbalance; cerebellopontine angle mass on MRI; bilateral = NF2",
          "Wallenberg / lateral medullary — vertigo with dysphagia, hoarseness, ipsilateral Horner and facial pain/temperature loss, contralateral body loss; PICA",
          "Cerebellar stroke / posterior circulation stroke — vertigo with ataxia (cannot walk), direction-changing nystagmus, skew, normal head-impulse test, diplopia; vascular risk factors; MRI",
          "Multiple sclerosis / MS — young woman, vertigo with internuclear ophthalmoplegia, optic neuritis or prior deficits; periventricular plaques on MRI",
        ],
      },
      {
        group: "Ototoxic drugs",
        items: [
          "Aminoglycosides / gentamicin — vertigo, tinnitus or sensorineural loss in the endocarditis patient on IV antibiotics; CN VIII toxicity; also nephrotoxic",
          "Cisplatin — chemotherapy ototoxicity (high-frequency sensorineural loss, tinnitus) plus peripheral neuropathy",
          "Loop diuretics / furosemide — ototoxic, especially rapid IV dosing or with aminoglycosides; ethacrynic acid worst",
          "Aspirin / salicylates — tinnitus is the first sign of toxicity; quinidine causes cinchonism (headache + tinnitus)",
        ],
      },
      {
        group: "Hearing-loss patterns",
        items: [
          "Conductive hearing loss — Rinne bone > air, Weber lateralizes TO the bad ear; cerumen, otitis media, otosclerosis, cholesteatoma",
          "Sensorineural hearing loss / SNHL — Rinne air > bone (normal), Weber lateralizes AWAY to the good ear; presbycusis, noise, ototoxins, schwannoma, meningitis",
          "Presbycusis — symmetric high-frequency loss of aging (vs Meniere's low frequency); trouble with consonants and background noise; hearing aids",
          "Audiometry / air-conduction audiometry — child with prior meningitis doing poorly in school → audiometry, not tympanometry (which tests eardrum mobility)",
        ],
      },
    ],
    pearls:
      "Sort vertigo by duration and hearing: seconds with position = BPPV; days after a virus = vestibular neuritis (add hearing loss = labyrinthitis); recurrent episodes with fluctuating low-frequency loss and tinnitus = Meniere. USMLE likes the mechanism: BPPV = 'otolith' (calcium carbonate otoconia loose in the posterior semicircular canal); Meniere = 'defective endolymphatic drainage'. Central red flags: vertigo with any other brainstem sign, inability to stand, direction-changing or vertical nystagmus, a normal head-impulse test, or a new severe headache — image (MRI, since CT misses the posterior fossa). Gentamicin ototoxicity can be vertigo without hearing loss. Weber lateralizes toward a conductive loss and away from a sensorineural loss — an NBME favorite is the unilateral sensorineural loss with Weber to the OTHER ear (schwannoma).",
    reviewed: REVIEWED,
  },
  // ─────────────────────────────── SEIZURES ───────────────────────────────
  {
    id: "headache-vertigo-seizure-seizure-types-first-line",
    domain: "headache-vertigo-seizure",
    name: "Seizure types & first-line drugs",
    org: MANAGEMENT,
    prompt: `Three patients: a 34M whose left hand twitched for a minute before he fell and had a generalized convulsion with tongue biting; a 9F who stares blankly 20 times a day for 10 seconds with eyelid fluttering and no confusion afterwards; and a 16M with early-morning arm jerks that make him drop his toothbrush.\n\nClassify seizures by onset and awareness, name the generalized types with their clue, give the first-line antiepileptic for each, and the workup after a first seizure.`,
    keyPoints: [
      {
        group: "Focal onset",
        items: [
          "Simple partial / focal aware — one region, awareness kept: rhythmic jerking of one hand, Jacksonian march, sensory or visual symptoms; focal EEG",
          "Complex partial / focal impaired — awareness lost, automatisms (lip smacking, picking), staring, postictal confusion; usually temporal lobe",
          "Secondary generalization — focal signs (one-arm twitching, aura) BEFORE a tonic-clonic seizure = focal onset (focal to bilateral tonic-clonic), not primary generalized; MRI for a lesion",
          "Temporal lobe epilepsy / mesial temporal — the most common focal epilepsy in adults: déjà vu, olfactory or gustatory aura, then focal impaired; hippocampal sclerosis on MRI; NBME's 'origin' answer",
        ],
      },
      {
        group: "Generalized onset",
        items: [
          "Tonic-clonic / grand mal — stiffening then rhythmic jerking, tongue laceration, incontinence, postictal confusion and amnesia; a normal tongue argues against seizure",
          "Absence / petit mal — child stares 10–30 s with blinking, no aura, no postictal state, many per day; hyperventilation provokes; 3-Hz spike-and-wave",
          "Myoclonic — brief shock-like jerks with awareness kept, generalized EEG discharges; looks like simple partial but the EEG is generalized; juvenile myoclonic epilepsy",
        ],
      },
      {
        group: "First-line drug",
        items: [
          "Ethosuximide — absence seizures; blocks thalamic T-type calcium channels; valproate if absence + tonic-clonic",
          "Valproate / valproic acid — juvenile myoclonic epilepsy and generalized/unclassified seizures; hepatotoxic, pancreatitis, weight gain, neural tube defects",
          "Carbamazepine / phenytoin — classic first-line for focal seizures; carbamazepine SIADH/aplastic anemia, phenytoin gingival hyperplasia and fetal hydantoin syndrome",
          "Lamotrigine / levetiracetam — broad-spectrum modern first-line for focal or generalized, preferred in women of childbearing age; lamotrigine SJS, levetiracetam irritability",
          "Lorazepam / benzodiazepine — the acute seizure and status epilepticus first-line; also febrile seizure only if >5 min; not a maintenance drug",
        ],
      },
      {
        group: "First-seizure workup",
        items: [
          "Provoked seizure / acute symptomatic — hypoglycemia, hyponatremia, alcohol or benzo withdrawal, bupropion/tramadol, fever in a child: treat the cause, no AED",
          "MRI brain + EEG — every first unprovoked seizure (glucose, electrolytes, tox screen, ECG too); CT first in the ED if trauma or focal deficit",
          "No driving / driving restriction — counsel after any seizure (state-specific seizure-free interval); also no swimming alone, heights, baths unsupervised",
        ],
      },
    ],
    pearls:
      "Awareness decides simple vs complex; spread decides partial vs generalized. A focal sign before the convulsion (one limb twitching, an aura, head turning) makes it focal with secondary generalization even though the convulsion looks generalized — and a focal seizure in an adult means look for a lesion (MRI). Absence vs complex partial staring: absence is brief, dozens a day, no aura or postictal state, hyperventilation-provoked; complex partial is longer, has an aura and automatisms, and leaves confusion. Carbamazepine and phenytoin can WORSEN absence and myoclonic seizures — avoid them in childhood absence and JME (valproate, lamotrigine or levetiracetam instead). Start a maintenance AED after two unprovoked seizures, or after one with an abnormal EEG/MRI or a nocturnal seizure. In pregnancy: lowest effective dose of lamotrigine or levetiracetam plus folate 4 mg. Todd paralysis: transient post-ictal focal weakness that mimics stroke.",
    reviewed: REVIEWED,
  },
  {
    id: "headache-vertigo-seizure-pediatric-epilepsy-syndromes",
    domain: "headache-vertigo-seizure",
    name: "Pediatric epilepsy syndromes",
    org: DIFFERENTIAL,
    prompt: `A 6-month-old with Down syndrome has clusters of sudden flexion of the trunk and arms on waking and has stopped smiling; EEG shows chaotic high-amplitude spikes with no recognizable pattern. Separately, a 4F has near-daily seizures of several types, is putting objects in her mouth again, and is not responding to two antiepileptics.\n\nName the pediatric epilepsy syndromes by age and semiology, their EEG signatures, the treatment for each, and the clues that mark a bad prognosis.`,
    keyPoints: [
      {
        group: "Syndromes",
        items: [
          "West syndrome / infantile spasms — 3–12 months, clusters of flexor spasms on waking + developmental regression; tuberous sclerosis, Down syndrome, perinatal injury",
          "Lennox-Gastaut — 3–5 years, near-daily seizures of many types (tonic, atonic drop attacks, atypical absence), refractory, cognitive decline; slow 1.5–2.5 Hz spike-wave",
          "Juvenile myoclonic epilepsy / JME — 10–16 years, morning myoclonic jerks (drops the toothbrush) then tonic-clonic; sleep deprivation and alcohol trigger; family history",
          "Childhood absence epilepsy / absence — 4–10 years, dozens of 10-second staring spells with eyelid flutter, hyperventilation provokes; normal intelligence; most remit by adolescence",
          "Simple febrile seizure — 6 months–5 years, generalized, <15 min, once in 24 h, with fever; 2–4% of children; benign, no AED, no imaging or EEG",
        ],
      },
      {
        group: "EEG signatures",
        items: [
          "Hypsarrhythmia — chaotic high-amplitude slow waves with multifocal spikes and no recognizable pattern; West syndrome",
          "3-Hz spike-and-wave — symmetric, generalized, three per second; childhood absence; brought out by hyperventilation",
          "Generalized polyspike-and-wave / polyspike — 4–6 Hz, photosensitive; juvenile myoclonic epilepsy",
          "Centrotemporal spikes / benign rolandic — school-age child with nocturnal facial twitching, drooling and speech arrest, normal development; outgrown by puberty",
        ],
      },
      {
        group: "Treatment",
        items: [
          "ACTH / vigabatrin — West syndrome; ACTH (or high-dose prednisolone) first, vigabatrin first if tuberous sclerosis (watch for retinal toxicity)",
          "Valproate / valproic acid — juvenile myoclonic epilepsy (usually lifelong) and Lennox-Gastaut broad-spectrum; lamotrigine or levetiracetam instead in girls (teratogenic)",
          "Ethosuximide — childhood absence epilepsy first-line; valproate if absence + tonic-clonic seizures; lamotrigine third",
          "Rectal diazepam / rescue benzodiazepine — febrile seizure lasting >5 min (lorazepam IV in the ED); antipyretics do NOT prevent recurrence; no daily AED",
        ],
      },
      {
        group: "Prognostic clues",
        items: [
          "Complex febrile seizure — >15 min, focal features, or recurs within 24 h; higher epilepsy risk; LP for meningeal signs, and consider it at 6–12 months if under-immunized or on antibiotics",
          "Developmental regression / hyperoralism — part of the West triad, and putting objects in the mouth again in Lennox-Gastaut = cognitive decline, poor prognosis",
        ],
      },
    ],
    pearls:
      "Age is the first sort: spasms before 1 = West; mixed refractory seizures at 3–5 = Lennox-Gastaut (often the evolution of West); staring spells at 4–10 = childhood absence; morning jerks at 10–16 = JME; nocturnal face twitching at 3–13 = benign rolandic. West triad = spasms + hypsarrhythmia + regression (two of three suffice); 1–5% of Down syndrome, and tuberous sclerosis (ash-leaf spots, cardiac rhabdomyoma) is the classic cause where vigabatrin wins. Febrile seizure: about a 30% recurrence risk, only a 2-fold epilepsy risk after a simple one; risk factors for recurrence are age <18 months, low fever at onset, family history. A child with meningeal signs, petechiae, or lethargy that outlasts the postictal period needs an LP; a complex febrile seizure alone earns a low threshold for LP plus EEG/MRI, not an automatic tap. JME responds beautifully to valproate but relapses on withdrawal; carbamazepine and phenytoin worsen it.",
    reviewed: REVIEWED,
  },
  {
    id: "headache-vertigo-seizure-status-and-mimics",
    domain: "headache-vertigo-seizure",
    name: "Status epilepticus & seizure mimics",
    org: MANAGEMENT,
    prompt: `24M with known epilepsy is brought in convulsing for 8 minutes with no return to baseline; glucose 96, oxygen saturation 88%. In the next bay a 75M with prior MI had a 'seizure' at church: he went pale and sweaty, fell, jerked for 10 seconds, and woke immediately with an unbitten tongue.\n\nGive the stepwise drug ladder for status epilepticus, then name the cardiac/hypoxic and the other non-epileptic mimics with the clue that gives each away.`,
    keyPoints: [
      {
        group: "Status epilepticus ladder",
        items: [
          "Glucose / thiamine — with ABCs: airway, oxygen, monitor, IV access, fingerstick glucose (D50 with thiamine if low), electrolytes, AED levels, tox screen",
          "IV lorazepam / benzodiazepine — first line (0.1 mg/kg); IM midazolam if no IV access, rectal diazepam pre-hospital; repeat once at 5 min",
          "Fosphenytoin / phenytoin — second line if still seizing after benzodiazepines; levetiracetam and valproate are equivalent alternatives; phenytoin fast = hypotension, arrhythmia",
          "Phenobarbital / anesthesia — third line: phenobarbital, or intubate and infuse propofol or midazolam under continuous EEG for refractory status",
          "Magnesium sulfate — eclampsia: seizure in pregnancy or postpartum with hypertension/proteinuria; then deliver; not benzodiazepines first",
        ],
      },
      {
        group: "Cardiac & hypoxic mimics",
        items: [
          "Adams-Stokes attack / arrhythmic syncope — child (or adult) with an arrhythmia or heart block: abrupt LOC with a few jerks from brainstem hypoxia; EEG normal; ECG/Holter",
          "Convulsive syncope — elderly with cardiac disease (aortic stenosis, AF, prior MI): pale, sweaty, brief LOC with jerks, NO tongue bite, no postictal state; NBME answer is 'syncope'",
          "Breath-holding spell — 6 months–5 years: tantrum, pain or fright → cries, exhales, stops breathing, turns blue (or pale), goes limp ± brief jerks; benign, check iron",
          "Carotid sinus hypersensitivity — elderly man faints while shaving or turning his head in a tight collar; carotid sinus massage reproduces a ≥3-s pause; vasovagal syncope is the tilt-table-positive one",
        ],
      },
      {
        group: "Other mimics",
        items: [
          "Narcolepsy / cataplexy — sudden loss of tone with laughter, daytime sleepiness, sleep paralysis, hypnagogic hallucinations; orexin deficiency; polysomnography; modafinil",
          "Psychogenic nonepileptic seizure / PNES / conversion — eyes closed, asynchronous thrashing, pelvic thrusting, long duration, no postictal state, normal prolactin; video-EEG",
          "Delirium tremens / alcohol withdrawal — tremor, tachycardia, hallucinations 2–4 days after the last drink; withdrawal seizures at 6–48 h; benzodiazepines, not phenytoin",
          "Hypoglycemia / electrolytes — glucose <50, acute sodium <120 (3% saline), hypernatremia lowered too fast, low calcium or magnesium; fix the cause, AEDs will not stop it",
          "Transient ischemic attack / TIA — NEGATIVE symptoms (weakness, numbness, vision loss) vs a seizure's positive ones (jerking, tingling that marches); Todd paralysis is the reverse trap",
        ],
      },
    ],
    pearls:
      "Definition: a seizure lasting >5 minutes or two seizures without recovery in between (the old 30-minute definition is gone). The ladder is benzodiazepine → loading antiepileptic → anesthesia; every step needs ABCs, glucose and thiamine, and a search for the cause (non-adherence, withdrawal, infection, stroke, tumor, eclampsia). Fosphenytoin can be infused faster than phenytoin with less hypotension and no purple-glove injury, but both need cardiac monitoring. Nonconvulsive status is the confused patient who never wakes up after the convulsion — get an EEG. Seizure vs syncope: tongue laceration (lateral), incontinence, postictal confusion for minutes to hours, and a raised prolactin favor seizure; prodrome of lightheadedness, pallor, sweating, LOC under 30 seconds with immediate recovery favor syncope (a few myoclonic jerks are normal in syncope). Adams-Stokes: the twitching child with a heart block needs a pacemaker, not an AED.",
    reviewed: REVIEWED,
  },
];
